# September 7th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/09/07/01/)_ {.unnumbered}

<br>

First of all, I would like to make a brief introduction. I would like to say that when I attempt to describe much of what I have been through over the 50 years I have been playing Yiddish theater in America, as well as a lot of what I heard and saw over these 50 years, I feel it exactly as if I were now for the first time – dressed in "vinegar and honey"^[Yiddish idiom meaning "dressed to kill"; "all dolled up"], released alone on a big stage in a huge theater, with the eyes of thousands and thousands of people turned to me; Everyone is waiting, everyone is looking out for something to hear something from me, but I'm standing in a panic, in a state of confusion and I don't know where to begin...

Well, really, what do I start with and what do I leave for later? 50 years on stage is no small thing!

50 years of acting!

50 years of singing!

50 years of dancing!

Over half a century, which has already passed and will never return, I knew the greatest and most famous Yiddish actors, the pioneers, the builders and founders of Yiddish theater in America; I was close friends with most of them, and about each one of them I have something to tell, although not everything can be told...

Where do I begin?

And suddenly so many events and moments that I had forgotten for a long time come to mind. I suddenly remember things I have not thought of for a long time. The figures of people who were once very close and who have now passed on float before my eyes. And when you mention their names and talk about what performed on the Yiddish stage in America and roles they created when they were at the top, you shake your head and realize that when they were alive, they were not appreciated enough, and that if they were alive now, people would know how to appreciate them...

And the more I immerse myself in what is now floating in my memory, the more it turns out that everything is gone, gone...
Away in the distant past, which is gradually being forgotten more and more.

I'm thinking about this now and even for me, the funny comedian on the Yiddish stage, it weighs heavily on my heart and I don't know where to begin.


It's a long way back...but still!
When you think about the long road you traveled, and you have in mind not only the others, but also yourself, it seems that everything was just yesterday...
That's why I will start with myself, and as I involve many others as well, and all in all, I believe my stories will reflect a piece of history of 50 years of Yiddish theater in America. I am sure that the thousands and thousands of Jews who are interested in the Jewish life of the past and present will find this interesting.

---

So, I will start with myself, as is usually the case in a memoir. And right from the beginning I want to say, not unlike many other Jews that came to America from Russia and from many other countries, I did not bring my name to America; My name was not {{< var sam-full >}} back home, but {{< var shmuelik-full >}}. That's the name they gave me. That's what everyone called me, and no one there, God forbid, ever thought about how difficult it was to get such a long name out...

I don't know what city I was born in. And don't think that this is some joke on my part, or a prank by a comedian who sometimes plays tricks on the stage. All my years I tried to find out what city, or what town, I was born in, but all my efforts were in vain and I couldn't find any talk about it, because there were two opinions: One opinion was that I was born in {{< var kyiv >}}, in the current capital of Ukraine; It was said that this happened just then when my mother visited {{< var kyiv >}} to see a very close relative of ours, who lived there in Solomenka^[A neighborhood right outside of {{< var kyiv >}} with a substantial Jewish population. In 1879 (10 years after {{< var sam >}} was born), it became part of {{< var kyiv >}} proper.]. More than once I heard my mother and father talk about this. And I was very satisfied that I was born in such a big city as {{< var kyiv >}}... To be born in the world, in a big beautiful city, and not some kind of wasteland {{< var shtetl >}} nobody has heard of or knows where it is...

But, as if to spite me, as though it was not {{< var beshert >}}^[fate/destiny] that I could take pride in this, there was a second opinion about where I was born - not in the big city of {{< var kyiv >}}, but in the small village of {{< var zat >}}, which is located between the two cities of {{< var bt >}}^[In Ukrainian, this is [Bila Tserkva](https://en.wikipedia.org/wiki/Bila_Tserkva)] and {{< var vasil >}}^[In Ukrainian, this is [Vasilkyv](https://en.wikipedia.org/wiki/Vasylkiv)], in the {{< var kyiv >}} Governorate.

I'm not sure what is true. We have this whole issue with us, the family is so confused, it was impossible to make sense of this. One thing, however, I am sure of, is that I was born.

The best thing about it is that I am alive and that for 50 years, I have been acting and singing and dancing on the Yiddish stage in America. I also know that now I am already, {{< var baruch-hashem >}}, 77 years old, and that means that I was born in 1869, when Alexander the 2nd was still sitting on the throne of Russia.

This was exactly eight years after {{< var panshina >}}^[serfdom, which Russia abolished 1861] was abolished in Russia and we were living in a {{< var shtetl >}}. I still remember those Ukrainian farmers well, who always told stories about the times during {{< var panshina >}} when the landowners could do with the peasants what they wanted.

In the village of {{< var zat >}}, where we lived for a long time, my {{< var tate >}}^["tateh" - father], {{< var Leybs >}}, had a farm, and that is why they called him {{< var Leybs >}} the {{< var Possessor >}}^[the farmer], and my {{< var mame >}}^["mameh" - mother] was called {{< var Feige >}} the {{< var Possessorka >}}. When he was home, he was doing business with the big landowner, Graf^[Graf is count/earl in Russian] Branitsky, who was the owner of the whole village and who also had a large fortune and was loaded with money.

{{< var Tate >}} was a constant presence in the landowner's court, and I still remember how every time, when he had to go to the landowner, he combed his beautiful beard in a very special way into two points, and when he came back, but he had to tell many stories about the strange nobles’ whims that he could not understand. And all the usual stories ended with the fact that he, my father, gave a thumbs-up and said:

-- _It's a nation/people!_^[Not a good translation here.]

And by this he meant, what is there say - it's his world, not ours...

He was a very {{< var frum >}}^[pious] Jew, my {{< var tate >}}. He carefully preserved Judaism with all the details and rules, and he shunned transgressions, just as one shuns fire. He also wanted his children to be {{< var frum >}} and devout. There were six of us children at home, two sons and four daughters, and {{< var tate >}} was afraid that we would became, God forbid, {{< var goyishe >}} from the village^[ They lived close to many Ukrainians]. He introduced that always, summer and winter, we should keep a {{< var melamed >}}^[Torah teacher/tutor] in the house for us, who should study with us. Not only with the boys, but also with the girls.

He also introduced that on {{< var shabes >}}^[Shabbat] or a {{< var yontif >}}^[Yom Tov; holiday] we should not be in the village. In the village, he said, a Jew cannot observe {{< var shabes >}} and {{< var yontif >}}. And that's why we all used to go to a Jewish hostel in the city on {{< var shabes >}} and {{< var yontif >}} where kosher was kept so meticulously that even the {{< var rebbe >}} himself would eat there.

After praying, he would always get joy from bringing some poor guests from the {{< var shul >}} to the hostel, and they would eat there at his expense. And {{< var mame >}} enjoyed it greatly; She was very pleased that {{< var tate >}} behaved in such a godly manner. And when she was well-rested, she used to say to him, with a loving smile in her eyes, "{{< var Leybs >}}, if {{< var hashem >}}^[G-d; literally means "the name" to avoid saying the word God.] wills your [120 years](https://en.wikipedia.org/wiki/Live_until_120), you will enter {{< var ganeden >}}^[Garden of Eden] right away..."

Sometimes he replied: “Well, what else are we living for?"

And at home, my father always behaved like a true {{< var frum >}}_mer_^[someone who is {{< var frum >}}], and he did everything he could so that we, the children in the house, would follow his ways. But living in the village had such an effect on us, that it was hard to walk always on the road that our father had led us on. The stillness of the nature around us attracted me like a magnet and when I could, I quietly slipped away from the {{< var melamed >}} and went outside and ran away. I crossed the dusty village roads and went to the wide fields that stretched far away, where heaven and earth meet, and I played with the {{< var goyishe >}} children and felt free, just like the birds that fly away.

I was very sly to sneak out quietly, so that the {{< var melamed >}} wouldn't see it. I was able to do this so quickly that even before people looked around I was already so far away that they couldn't see me. And I already had my own roads to run and my own places to play in. And I wasn't afraid of anyone, because I was an overprotected child; My parents have always given me a lot, they have loved and pampered me. And I was always sure that they would not punish me. I don't know why I was praised so much. It could be that it was because I was so little, a little elf, and who looked so pitiful so nobody has the heart to treat me too harshly. But no matter what - I was blessed that I could do what I wanted, and I always avoided punishment...

Of all the things in the village, I liked more than anything the crowd of the young Ukrainian farmers and peasants. I really liked to see how they dance to the beat of a harmonica, which can be seen so widely while playing, that it is simply a pleasure to watch. More than once in the village I followed them to the Ukrainian chapel, where they played at a {{< var goyishe >}} wedding. I could not take my eyes off the dancers, who danced so much that the ground really shook under their feet. And when I came home afterwards, I danced all day long, those dances which I liked so much. And once, when the father saw this, he gave me a tug on the shoulder and taking both tips of his beard in his hand, he said:

-- Just look, just look at the little {{< var shmuelikel >}} of ours dance!... What's so great about you? What are you skipping and frolicking around for?

I was very ashamed then. Why did I jump around so much in the middle of it? But just as quickly {{< var tate >}} left the house, he gave me a hug, and then I just danced again^[This is a Ukrainian folk song, [not unlikely this one](https://www.mamalisa.com/?t=es&p=5520)]...

> Hop, moyi hrechanyky^[buckwheat blintz ("blini")],
>
> Hop, moyi mili^[{{< var sam >}} writes _mili_, but the folk song linked above says _bili_. Still, likely the same song and possibly a typo in {{< var sam >}}'s article.].

It was good for me. I was happy...




