# Two weddings and a funeral

::: {style="text-align: right;"}
_Published in the {{< var forverts >}} on [September 21st, 1946](https://www.nli.org.il/en/newspapers/frw/1946/09/21/01/)_
:::



As far as {{< var tate >}} was concerned, he thought that while preparing for the wedding, people would not think about how he was a crippled invalid. Because of this, he got out of bed several times during the day and, walking around the house with a cane, he bathed and looked at everything that was bought for {{< var Batsheva >}}. Excited for the occasion, he also thought that aside from inviting the in-laws, we shouldn't forget any of the poor relatives who lived in the nearby towns around and around. Every time he remembered something, someone else hugged him, and he said, "For God's sake, we should not forget it." He also announced that it should be seen that there should be as many poor guests as possible for the {{< var chuppah >}} meal.

-- Just don't steal any money, {{< var Feige >}}." - he said to {{< var mame >}}, who then, even more than he, put on a dark face, so that you wouldn't see the heavy thoughts she carried because of his illness. - Just don't begrudge any money!... It costs so much, it will cost even more. God is our father and he will not forsake us...

And {{< var mame >}} did what {{< var tate >}} told her. And as soon as it became clear to her that he was dragging himself around the house too much, she beseeched him:

-- Follow me, {{< var Leybs >}}, and lie down. You are already tired and you need to rest. And believe me -  she continued leading him to the secluded alcove where he was lying - believe me that our daughter's wedding, God willing, will turn out fine, and it will be good...

And so it was.

At the wedding, which took place two weeks before {{< var pesach >}}, in the small village of {{< var zat >}}, which is located between {{< var vasil >}} and {{< var bt >}}, so many celebrants came that even at a fair you never saw so many people. There was not a single Jewish landowner in all the surrounding {{< var shtetl >}}_s_ and towns at that time who did not come to the wedding. Among all these guests, Jews with large orchards and with a lot of strength and courage, there were {{< var chasidim >}} of the {{< var Makarover >}} {{< var rebbe >}}. {{< var Tate >}} did not invite any other {{< var chasidim >}}^[as in, no other kinds of {{< var chasidim >}} - only {{< var Makarover >}} {{< var chasidim >}}]. He would certainly not have them at the doorstep of his house. And the Jewish landowners did not come alone, but with their wives and children, and they drove to the village in horse-drawn carriages. Just as they felt at home among the Jews, so they felt at home among the {{< var goyim >}}, and they spoke the {{< var goyishe >}} language Ukrainian just as freely and easily as they spoke Yiddish.

For each landowner who came to the wedding, and also for the other celebrants who came from the {{< var shtetl >}}_s_, they made way for Abba the Klezmer musician with his band of musicians, who were brought down from {{< var bt >}}. He, the Abba the Klezmer musician, was a smart, driven Jew, who even then, even in those times, wore a pressed shirt, a top and a short cap that falls to the waist. He wasn't born yesterday, and he knew how to play music for a high-ranking courtier, for whom a "_kerbel is a mumzer_"^[idiom: "a ruble is a trifle"; as in, money is no object].

And the greatest wears brought for my sister {{< var Batsheva >}}'s wedding were from the rich landowner {{< var eliezer-shmuel >}}, who had a reputation for being a very wealthy man with a generous hand. In front of him, Abba played something like "Vivetsh" and something like "Dobrivetsh" with the band, over which {{< var eliezer-shmuel >}} himself was truly beside himself with joy and he said that he had never heard anything like that before...

The {{< var simcha >}} was great. The whole village of {{< var zat >}} went mad with the wedding we held. Our goyishe neighbors, simple farmers and peasants, felt like family and they also came to the wedding and gave gifts and they danced and they congratulated the groom and the bride. May they be blessed and never know any evil...At that time, Jews and goyim still lived in peace among themselves in the villages...The {{< var goyim >}} only began to show hatred towards the Jews only later^[At this time in Pale of Settlement history, things were overall good for the Jews], when they were urged, when they were persuaded Jews were to blame for all the troubles that befell them...

But no matter how great the {{< var simcha >}} was when Jews and {{< var goyim >}} were together at my sister's wedding in the {{< var shtetl >}}, the joy was still a little bit overshadowed, because the whole time {{< var tate >}} was so ill and he felt so weak that, cane in hand, while sitting from the table watching everyone dance and rejoice, his head soon turned and his face became pale and he was led away back home to lie down in bed to rest. {{< var Mame >}} usually was the one to take him home. She was always the first to notice how pale his face became when he sat down among the celebrants at the table. And he didn't resist when she led him back to rest. Leaning on his cane, he walked with a strange smile on his pale face. He no longer had even a trace of the determination, of the {{< var possessor >}}'s firmness that he used to show before he got sick. And walking like this with {{< var mame >}}, he comforted and reassured her:

-- It's not over, {{< var Feige >}}, it's not over... It will soon pass when I will come out to celebrate again... It's not over! Let us rejoice! Let us dance! Let us be happy!

As far as he could, he gathered all his strength, and with {{< var mame >}} he led his daughter to the {{< var chuppah >}} - the first daughter of his, whom he had married off before she was even born...

The new {{< var kapote >}} which he wore hung loosely on him, because he was already so emaciated and weak. But his face still shone. You could see that he felt happy that he led his first child to the {{< var chuppah >}}. And when she arrived to the {{< var chuppah >}} we danced. When I saw how he {{< var kvelled >}}, how he danced in the {{< var kapote >}}, how he was clapping his hands, I suddenly had such a strong desire to make him happy that I didn't know what to do. And then I ran up to him, grabbed both his hands and started kissing them; Tears fell from my eyes. Tears of joy, and soon I got so excited and started dancing that it was impossible to stop myself... And father was full of {{< var naches >}}^[joy/pride].

-- Dance, {{< var shmuelik >}}!

He encouraged me and when I ran up to him again in joy and kissed his hands again,

-- Dance {{< var shmuelik >}}! At a wedding one should dance... at a wedding one should be happy...

And four weeks after the wedding he died.

---


After {{< var tate >}}'s death, {{< var mame >}} got involved in the heavy burden of making a living. She started to lead the farm by herself, and people started calling her "{{< var Feige >}} the {{< var Possessorka >}}." But soon she began to realize that {{< var tate >}} was not at all as capable as he thought and that he had spent much more and lived much larger than he could afford... For two years, {{< var mame >}} struggled with the farm, and it was difficult for her to get out. {{< var Tate >}}'s fields, his broad orchards, the land they owned in the village could not go as it went before. It was no longer possible to afford what we could when {{< var tate >}} was still alive. It was already something completely different from what it was...

Even a permanent {{< var melamed >}} for the children could not be kept. And at the time that this did not bother me, because to date I have never shown any great desire, and now it often bothers me very much...

But life went on there, and during the times when {{< var mame >}} was tormented by the poverty-inducing property, she married off my older brother, {{< var itzhik-gedolia >}}^[later, he became Isaac Casten in America], who was nicknamed {{< var katik >}}^[kitten] in the family - he was quiet like a little kitten who plays only in a corner. {{< var itzhik-gedolia >}} was married to the daughter^[her name was Chuna, later changed to Anna in America] of a certain {{< var shmuel-pekelis >}}^[It is worth noting that {{< var sam >}} may be misremembering his name. According to [Anna's gravestone](https://www.findagrave.com/memorial/152164678/isaac-casten#view-photo=240653611), her father's name was Isaiah-Leyb, not Shmuel.], a Jewish merchant, who lived in {{< var bt >}} and conducted business with other cities as well.

And at that wedding of my brother {{< var katik >}}, I saw and heard for the first time the [{{< var badchen >}}](https://en.wikipedia.org/wiki/Badchen) {{< var shakhnes-full >}}, who at that time had a reputation in many Jewish cities and towns of {{< var kyiv >}} Governorate and also in the Podolier province. He really became an artist in his profession, {{< var shakhnes-full >}}, and he behaved as if he wanted to make a whole dynasty out of it.


People already knew that he doesn't perform at weddings by himself, but was accompanied by his son-in-law who helped with the performance to earn room and board. The {{< var badchen >}} was {{< var shakhnes-full >}} alone, and he performed in such a way that the women would shed tears. And after {{< var kalebes >}}^["Serenading of the bride," a popular Jewish wedding song. [Listen here](https://search.library.wisc.edu/digital/AHMP2C6SE53XOV8O/ABJC2CTJMIPMKT8X).], he performed a scene that his son-in-law helped with. And I still remember the scene that he, {{< var shakhnes-full >}}, played with his son-in-law at my older brother's wedding after the {{< var kalebes >}}, which made all the women weep.

{{< var berele >}} himself then stood with his pointed beard and struck such a pose, as if to say you could rely on him and be sure that soon you will see something that is worth all the money. And as he was standing like that, his son-in-law showed up disguised as a beggar, and soon he started singing a very sad {{< var nigun >}}^[singular {{< var nigunim >}}]:

> I walk around in the street
>
> One by one,
>
> I ask people for money/alms,
>
> But they don't want to look at me.

He sang it one time, and then a second time. And immediately afterwards, he begged - "Give me alms!"

And then {{< var shakhnes-full >}} the {{< var badchen >}} released such an anger on the poor beggar, and they began a dialogue:

-- {{< var berele >}}: Hey, you pauper, why did you come here just to make the wedding guests sad? This is a wedding where everyone should be happy!

-- Beggar: But how can I be happy, when I am a poor Jew begging for money?

-- {{< var berele >}}: You must be happy!

-- Beggar: I must?

-- {{< var berele >}}: Yes, you must!

-- Beggar: {{< var Nu >}}, if I must, you have to show me how. Come on, let's see how a poor Jew like me could be happy!

-- {{< var berele >}}: I will show you! Indeed, I will show you!

This is how the dialogue went between the {{< var badchen >}} and his son-in-law who was pretending to be a beggar. And when they were done with their "lines," both sang to each other:

> Make merry, pauper,
>
> enjoy yourself, poor man;
>
> He who has nothing,
>
> really has it all.


We really liked watching them. I really enjoyed it in particular, and I can say that this was the first time in my life that I had ever seen theater. Yiddish theater. And to this day, I still think about {{< var shakhnes-full >}}' performance, as the first Yiddish actor I ever saw in my life...
