# September 25th, 1946

_Tate_'s death shook life of our entire family so much that things could never be as they were. No matter how hard _mame_ tried work hard so that we would not be in need or have to ask for help, she could not make it happen. It never happened. And then the name name "Feige the _Possessorka_" began to sound like a joke, because a _possessor_^[farmer] is a generally a professional who has means to live well.


When _mame_ lost all interest in running the property as _tate_ had, she left the village and settled in the town of Rybinka, where my sister Bat-sheva lived with her husband. And there, in Rybinka, we opened what is called a "_praseach-shtib_,"[^just think of this as a _general store_ - I will use that term moving forward.] where they sell everything that you can think of - even a little drink too.
_Mame_ worked very hard in the "general store," and she was really a great _eyses-kha'yel_^[term referring to an "industrious and capable wife"] and knew how to get along with people. Not only with the Jewish customers, who bought various small things from us, but also with the goyishe customers. She understood who could be given a loan, and who could not. And she behaved such that people in the town had a great respect for her, and they still called her "Feige the _Possessorka_."


A _possessorka_ without a _possessieh_^["A farmer without a farm."]. _Mame_ couldn't figure out what to do with me. She was of course sure that a woman - a widow - could still raise her daughters and, as it were, stay on the right path, such that when people see them, they will see beautiful and well-behaved children.
But with a son, it was more difficult. Especially with such a little son, who was a bit over-confident and doesn't show any great desire to learn...
Just like _tate_, _mame_ also wanted me to grow up to be a _mensh_ and to study, if not a lot, at least a little. And because of that, she took me to the Beyala-Tserkov and there she put me in the _heder_[^essentially a yeshiva] of Chaim Machalies, a _melamed_, because she heard that he, is a very good _melamed_ and that the children of the finest and most honorable families learn from him.

"Look, Shmuel'ik," she announced to me, "put your head down to study, you will be a scholar. A Jewish boy must be able to learn."

When we lived in Beyala-Tserkov, I lived with our father-in-law Shmuel Pekelis, the father-in-law of my brother Yitzhik-Gedolia, who was given the nickname "Katik" because he was as quiet as a kitten. Shmuel Pekelis himself promised that they would keep me at home like their own child and that nothing would go wrong. And so it was. They kept me at home like their own child and they took good care of me. But the trouble was, that because I was an orphan^[his mother is alive, but he still uses this term.], I was watched over a little too closely. I just had to do one little thing, and I was immediately reprimanded for it:

-- "This is not acceptable, Shmuel'ik. Not acceptable. Your mother is doing everything so you can be in the _heder_, and this is how you repay her...

The truth was that I was no ordinary boy. On the contrary, I was actually a quiet boy and I didn't catch anyone's eye too much. In addition, I always kept myself very clean and neat, and when someone gave me a new outfit, my eyes really lit up. I preserved it in such a way that it always looked brand new, as if it had come straight off the needle. What’s more - I had a tendency to sing every song that I heard in the street. As soon I heard it and immediately I was singing it. And if the song could be danced to, I danced to it.


And all the people who were so watchful over me did not want me behaving this way, and they scolded me: "What is the big deal with you? And what you doing, dancing in _mitzke-deritzke_^[maybe this means "middle of the street" in Ukrainian]?" And sometimes they also brought up I am an orphan... An orphan must not sing. An orphan should not be happy. 

Also, my brother Yitzhik-Gedolia, the silent "Katik," used to come from time to time to the Beyala-Tserkov from the village of Solovinke, where he sold grain. He also scolded me and told me how to behave - so that everyone in the home, including his father-in-law and mother-in-law, would be able to say that I was just as quiet as him. And this, in the end, was too much for me, and I couldn't take it anymore. I also longed for my mother very much, and so I begged him, my silent brother:
- Do me a _toiva_^[literally "a good" - means favor. I'm pretty sure it's pronounced toiva in Sam's yiddish dialect, but it's spelled tova (hebrew).] and take me back home. I've been here enough. I don't want to be here anymore. I'd rather go to the _heder_ in 

I also asked my _mame_ to let me come home. And when they finally gave in to me and they brought me back to Rybinka and I was once again home with my _mame_, they send me to _heder_ with the _melamed_ Shmuel-Yossel, and this alone meant I could not have any joy; nothing good could come of this. He was an angry Jew, the Shmuel-Yossel. A Jew with a red beard, a broad physique, and with two large, glaring eyes. He did not know how to speak to a student with kindness; He was always angry, the anger always sat in him, just like in a cauldron. And when he had his two big eyes, the glaring ones, focused on a student, it felt like "the value of congealed/hardened mother's milk"^[well this is quite the idiom..! It's clearly not a good thing.] and he was overwhelmed with fear.

Thought I wanted to keep the promise I made to my _mame_ that I would study well in the _heder_ at Rybinka, I was unable to do so. It was absolutely impossible to learn anything from such a _melamed_. We all hated him in the _heder_. His wife, an overburdened woman, who sold apples in the market, also hated him. And her hatred towards him was not in vain, because there was rarely a day that goes by that he did not beat her. And always, when he hit her, she screamed with loud voices, "Save me, Jewish children! He is going to kill me, the murderer...!" Of course, I could not learn much Torah from such a _melamed_. Every day in the _heder_ was a punishment for me.


And from that time I remember something, which was strongly imprinted in my memory^[Remember this story for later - it will come up again. Once that chapter is written I will come back and link it here.], and I want to tell it here:
This was on a hot summer day, soon after lunch. In the shtetl, there was suddenly a stampede. And when the rabbi went outside to see what was happening there, he immediately ran back inside and shouted at the top of his voice: "Come, _shkotsim_^[Literally this is some kind of little pastry or meatball, so it is probably an idiom referring to the children], with me!"

In a hurry, he grabbed his kaftan and went out quickly, and we all ran after him, wondering where he is taking us - we were afraid. We followed him and none of us said a word the whole time. And so we went until he led us all into the _Beit-Midrash_ and there we saw something I will never forget. 

In the middle of a circle of inflamed and very mortified Jews stood a frightened man, Meir the poet, who at that time used to go to a nearby town to pray on Shabbat in front of the pulpit. We knew that he was the son of the Rakitner rabbi, and that the butcher in Rybinka, Yehial, was his brother. He was a very young man, Meir, and he always behaved as if he had no fear of anyone in the world. This time, however, he stood trembling in fear, and the enraged Jews shouted at him, called him the worst names, and one of them, an angry Jew, an instigator, punched.

-- Well, you throw someone out! ... Oh you, you _Ocher-Israel_^[derogatory term for a heretic], who are you!...
This was still little, he was also laid over and the real lashes were added to him. And it didn't help to wrestle with them; Meir could not stand alone against so many people and he had to accept the punishment that was given to him.


