# September 28th, 1946

##### _Link to [{{< var forverts >}} edition](https://www.nli.org.il/en/newspapers/frw/1946/09/28/01/)_ {.unnumbered}

<br>


Considering what happened at that time, you would think I would have remembered something more from when the tsar, Alexander the Second, was killed in Russia. This happened in 1881, when I was already a 12-year-old boy - "approaching 13" as we used to say in Ukraine. But there isn't a single thing left in my memory about that important event in Russian history. And if I used to know something, I covered it up and I don't remember it.

I also remember very little of the pogroms that came after the tsar was killed - the pogroms of 1881 and 1882, when Alexander the Third ascended the throne and Jews started fleeing from Russia wherever their eyes could see because it was no longer safe to stay. I only remember one story from the time we had pogroms, and I will tell it here.

I remember how one day in {{< var rybinka >}}, we suddenly heard the bells ringing in the church, and that alone was enough to strike fear into the hearts of the Jews. And suddenly, the farmers^[specifically the {{< var goyishe >}} farmers] came from all around and started going into the church. Many farmers also came from the village of {{< var solovinke >}}, which was separated from the town by a river. They all started arriving from the other shore and immediately went to the church. And when the Jews of the town saw this, they said that nothing good would come of it, and the mothers began to hide the children. There was such a panic that no one knew what to do first and where to hide.

And the bells of the church kept ringing and ringing and the more they rang, the greater the fear became, and we were certain we would not be able to escape the impending calamity...

But it turned out differently; The {{< var goyim >}} left the church quiet, calm, and they went home without bothering anyone. Later we found out that the good priest, who was always a close friend of the Jews, saved the village. He heard that the {{< var goyim >}} were preparing to stage a pogrom on the Jews of the town, and he promised himself that he would do whatever he could to prevent this; He did not want there to be a pogrom in the town and for Jewish blood to be shed for no reason. Because of that, he called the {{< var goyim >}} into the church with the bells, and he gave them a speech that God would punish them severely for such a sin. And this had such an effect on them that they left the church and returned home quiet and calm; They didn't bother the Jews in the town, and there was no pogrom.

The Jews in {{< var rybinka >}} then breathed more freely. They thanked God for the great miracle that happened and they treated the good priest as if he were a {{< var tzaddik >}}. But people were not entirely sure whether he would be able to continue protecting the town from a pogrom. We began to hear rumors that so-and-so had left for America, and so-and-so had his eye on leaving for America. And when they talked about it, they didn't say that they had left for America, but that they had _fled_ to America. You never traveled to or visited America - you _escaped_ to America.

Every letter that arrived from America was usually passed around hand to hand, and people talked about the letter as if it was the most important news that happened. In particular, when a picture of someone who had "escaped to America" arrived, people walked around with it as if it was just a great pleasure and they simply couldn't tear their eyes away from it and everyone gaped:

-- You can't even recognize them... they have become completely different people in America... you can see that they live there like noblemen...!


And also in our family, people started talking about going to America. The first was my oldest sister, {{< var Batsheva >}}; She was the first to go to America, together with her husband. They settled in Philadelphia. And even though from the letter that they wrote to us from there, it was clear that they weren't making much money from "dragging the shovel"^[This is either a mistranslation (most likely), or an idiom, or perhaps it refers to farming?], we still started to prepare for the journey. At that time, {{< var mame >}} started saying quite openly that she would not stay in Russia - she would take the children and leave with them for America.

It was difficult to earn enough money for the household from the general store that {{< var mame >}} ran in {{< var rybinka >}}. In general, it was difficult for Jews in Russia when Alexander the Third sat on the throne; what they wanted to do, was not allowed. So many things were forbidden for Jews, and we were at the mercy of the _pristav_^[the tsarist Russia governance police superintendent] and sometimes the _sotski_^[the tsarist Russia local police].

{{< var Mame >}} continued to act like the kind of person people assumed she was - the successful business owner - and that we wanted for nothing, and she should still be thought of as "{{< var Feige >}} the {{< var Possessorka >}}."

But there were times when we weren't able to afford necessities; And we all worked in the "general store" - {{< var mame >}}, the three daughters, and me^[Recall, there are six children: two boys and four girls. So far, one boy ({{< var itzhik-gedolia >}}) and one girl ({{< var Batsheva >}}) have married]. There was always something to do in the "general store," but there was still no income.

{{< var Mame >}} always wanted to be able to pay her debts on time and not owe anything to anyone. So we struggled for a couple of years until my sister {{< var Batsheva >}} started writing better letters from America. Then, {{< var mame >}} sold the house and everything she could, and she took us, her four children, with her to America.
This was, I believe, in the year 1885, and at that time I was already a young man of about 16 years, going on 17. And I was very happy that we were going to America, and I bragged about it to all my friends.

-- You'll see what will happen! In America, we will become such people, and so it shall be! In America it will be - none of your business!^[This is a Ukrainian phrase he uses which could alternatively be translated as "don't start with me"]

I still didn't know what I would become in America. I didn't even have the slightest idea about theater at that time. The only piece of "theater" that floated through my memory from time to time was the comic scene that the {{< var badchen >}} {{< var shakhnes-full >}} performed together with his son-in-law at my older brother's wedding. It seemed to bother me - that if they would have let me, I would have done it even better; It occurred to me then, that when I am older perhaps they will let me do this in America for a wedding, I will show them what I can do and then, in time, I will become a second {{< var shakhnes-full >}} in America...

I could not have imagined a better entertainer than him, {{< var shakhnes-full >}}, at that time. So it occurred to me that the best thing I could do was follow in his footsteps, and before leaving for America, I often sang the song that I heard him sing:

> Make merry, pauper,
>
> enjoy yourself, poor man;
>
> He who has nothing,
>
> really has it all.


It was good for me; I dreamed of a happy life in America, even before I arrived there. And when another friend asked me why I was so eager to go to America, I had one answer: "What is it that you say? It will be as I told you - none of your business!" And I said this in good fun; I didn't get angry with anyone.

We fled to America just as thousands and thousands of other Jews did; We crossed the border in "blackness"^[specifically means they illegally crossed the border]. That's what people called it when they snuck to get passports while hiding from the special officers who patrolled the border at night.

And I still remember that when we crossed the border and we arrived at Brod^[Yiddish name for Brody, Ukraine. At this time, the city was part of Poland.], we had trouble with our agent, because he didn't want to let us take our suitcases without more money^[a bribe]. This made {{< var mame >}} angry - she said this was murderous and violent. But it didn't help at all, and we had to give the agent more money.

It is impossible to describe the troubles that poor Jewish travelers had at the borders in those years when they "escaped to America." But it was still better than it is now^[Recall this is being written in 1946 when there are many Jewish refugees with nowhere to go after the Holocaust]; You didn't have to have a visa, nobody needed a passport, and you could go wherever you wanted...

On the way, we waited for a little while in the German city of Bremen, and then we, along with many other Jews, were put on a ship. "Elbe," I remember, was the name of that ship. We {{< var schlepped >}} ourselves across the sea for two and a half weeks until we finally arrived in America. This was on a hot summer day, and when I saw the city of New York for the first time in my life, I opened my mouth and ears; I literally swallowed everything I saw with my eyes, and the strongest and best impression it made on me was how people walked around the city dressed so beautifully...

I liked this very much and I envied them all. Happy people. Even during the weekdays, they dress up like it's {{< var yontif >}}... Can there be any greater happiness in life?...

That's what I thought then, because even from a young age I liked to dress nicely and keep myself neat. I always wanted to do something that could make my daily life more like a {{< var yontif >}}, and that's why I probably became an actor...

We were not in New York for a long time, not even a few hours. From there, we left on a train to Philadelphia, where my sister {{< var Batsheva >}} lived with her husband. And as usual, in the first few days, the happiness was great. After that, people started thinking about what one can do in America to "make a living." As it turned out, that the best thing I could to "make a living," in America, was - selling bundles of matches in the streets...

When I heard this, my eyes immediately went dark.

-- What do you mean, selling matches in the streets?! Why did I come to America?

But it didn't help at all; Everyone made me understand that, in America, first of all you have to get the {{< var meshugas >}} out of your head, and second, everyone here has to work, because otherwise you can't "climb the economic ladder." Other than that, you don't have to worry about anything in America. The main thing is to earn money and make a living...

And this is how it happened: They hung a cash register around my neck. A cash register with a box of matches. I was placed on South Fifth Street^[At this time, the Jewish district in Philadelphia was roughly Locust - Christian, 8th - Front. The stretch of Bainbridge between 4th-5th was a market, so I imagine {{< var sam >}} was around that area.] and ordered to walk back and forth and exclaim aloud: "Parlor matches, t'ree^["three"] for five! Parlor matches, t'ree for five!" the whole time...

The foreign words did not roll off my tongue, even though I learned them well before. I ended up styled them in my own way and it came out something like, "Palner mentsh't is priper fieft!"

But it didn't take more than a couple of days for me to learn those first English words I knew in America. I had to have a new livelihood, and I was already calling out my goods like a happy merchant, hanging around with a cash box on South Fifth Street in Philadelphia: "Parlor matches, t'ree for five!"

This was my first income in America. And I've already "made a living" and I was already "alright."








