# October 3rd, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/10/03/01/)_ {.unnumbered}

<br>


Selling matches on the streets of Philadelphia become something of a game for me, not just a way to make a living. That's how I approached it. And little by little I became so interested in the various people who bought the matches from me that I didn't just call out my goods for sale, but I sang them out in my own way: 

-- Parlor matches, three for five! Parlor ma-a-a-tches, three for fi-yi-yi-ve!

And in my mind, something of that {{< var nigun >}}, which I heard from the {{< var badchen >}} {{< var shakhnes-full >}}, lingered... 

I didn't make any great fortunes, but still I considered myself a "big earner." And when I bought a suit with my own money and dressed like a real _American boy_^[written "_Amerikaner boi_": אמעריקאנער באי], I was literally in seventh heaven and felt like no one was my equal.

That's how I passed the time, and I picked up a lot of English in the street, and I even was able to argue even with a policeman. And then a [Galician Jew](https://en.wikipedia.org/wiki/Galician_Jews) suggested to me that I join him in nearby villages and we could earn a bit of money there. He was a peddler, the Galician Jew, who made the proposal to me; He sold towels and tablecloths and laundry and handkerchiefs and other such things, which he kept in a heavy suitcase. With this suitcase he {{< var schlepped >}} around the nearby villages around Philadelphia, and there he already had customers everywhere, even regular customers who bought from him on loan. He toiled hard and saved as much as he could, because he wanted to bring his wife and children to America as soon as possible.

Every time he came into our house, he talked about it and complained that he was just a wandering foreigner without a home; He really wanted to have a home and moreover, he really missed his wife and children whom he left behind in a some {{< var shtetl >}} in Galicia; He also complained that he had trouble {{< var schlepping >}} the heavy suitcase around the surrounding villages, because he was afraid of dogs...

And apparently, that is actually why he wanted me to go with him to the villages; I will sell my matches, the "parlor matches" sold at the price of "three for five," and he will sell his towels and tablecloths and all the other things that he carried in the heavy suitcase. It would be more {{< var haimlicher >}}^["homey" or "like home," implying a comfort/ease].

He was sure that with such a smart and lively young man like me, he would no longer need to be afraid of the dogs, and moreover, he wouldn't feel so miserable and he would have someone to speak to in Yiddish. The Galician Jew talked for so long to my {{< var mame >}} until she agreed to give her consent for me to join him in the villages. And that's how I became a villager in America...

I later picked up the English language in the villages. I even learned a couple of English songs and sang them. And the Galician Jew with the heavy suitcase was very pleased that I had joined him; He wasn't so lonely and cheerless anymore with me coming along, because I was always happy; In everything I did, above everything else, I found the "comedy"^[he keeps a sense of humor about everything], and when my heart was in a good place - whether I sold a lot of matches, or for some reason or another - I would sing out at the top of my voice.

I would sing out the songs I knew - in Yiddish, Ukrainian, and also English - along my way to the nearby villages, and anyone who could spare a shilling would buy matches from me.

In one village, a young woman - a Christian - caught my eye; I liked her so much that when I came to her to sell matches, she welcomed me as a very distinguished guest, and it almost became love between us. She twisted my head so much that I walked around bewildered, as though in a haze. But this is something it's best not to talk about...


---

After a while^[{{< var sam >}}'s [Lekskion](https://www.museumoffamilyhistory.com/yt/lex/K/kasten-sam.htm) entry suggests he sold matches for about a year. So, we can place the time in mid-1886], I was tired of {{< var schlepping >}} around the villages, and I was really sick of selling matches. I could no longer say the same thing and the same thing over and over again: "Parlor matches, three for five...." I was simply disgusted by it. And then a {{< var landsman >}}^["countryman," specifically implying someone from the same region in the old country] took me into his shop and taught me the craft of sewing shirts...


I became a "shirt-maker,"^[שירט–מעיקער] as it is called in America, and among the other {{< var landsmen >}} who worked there, they said that this is better than pearls, because in America trade/craft is a {{< var brokhe >}}^[from Hebrew, "bracha" meaning blessing]...

Working in the shop was completely different in those days than it is now; People worked longer hours and labored much harder than now. But one of the things that made working in the shop stand out at that time was that people sang while working...

And I really enjoyed that.

What _didn't_ Jewish workers sing while working in the shop! They knew all the songs from {{< var shulamith >}}^[An [operetta](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/shulamis-oder-bas-yerusholayim) by [{{< var goldfaden-full >}}](https://en.wikipedia.org/wiki/Abraham_Goldfaden), the father of Yiddish theater.], from {{< var barkochba >}}^[Another {{< var goldfaden-full >}} [operetta](http://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/bar-kokhba-der-zun-fun-di-shtern-oder-di-letste-teg-fun-yerusholayim)], and from the other Yiddish plays inside and out. In addition, they knew many other Jewish songs. Beautiful folk songs, which evoked the warmest feelings in everyone. And together with the noise of the machines, or better said, over the noise of the machines which had been working full-speed since the early hours of the night, the air was full of songs of love and other heartfelt Jewish folk {{< var nigunim >}}...

Jews who came to America from different countries - from Ukraine, from Lithuania, from Poland, from Galicia, from Romania, and from anywhere else - all worked and sang in the shop. And everyone brought with him a different style, different nuances, and sometimes even a new song that we hadn't heard before. And everyone sang. We couldn't not sing while working. It was very difficult to imagine how work in the shop could have gone without it...

And it's safe to say that we often sang [{{< var chazanishe >}}](https://en.wikipedia.org/wiki/Hazzan)^["{{< var chazan >}}"-ish; cantorial, religiously-inspired] tunes as well. The workers would sing {{< var chazanishe >}} {{< var shtiklakh >}}^[little bits of {{< var chazan >}} music] like this, going up like smoke^[unclear idiom here, but presumably a good thing - filling the air maybe?]. And it was normal that, that in the middle of the day, amidst the noise of the sewing machines, you could hear voices:^[Below I've directly written the _Hebrew_ (not Yiddish) as {{< var sam >}} wrote it out. This is a liturgical tune?]

> יעלה, יעלה תחנו–ני–נו מערב
>
> ויבוא שועתי–נו–נו מבוקר
>
> ויראה רנוני–נו–נו עד ערב

And soon everyone has has joined in, and it would become a "sing-along" in rounds. I remember how once our {{< var landsmen >}} in Philadelphia suddenly started making a fuss^[has a positive connotation here] about a new {{< var chazan >}} who came to {{< var daven >}}^[pray] in the "Russian _Shul_"^[In general, and certainly in Philadelphia, Jews attended a {{< var shul >}} founded by their {{< var landsmen >}}. [The "Russian _Shul_"](https://en.wikipedia.org/wiki/Historic_Congregation_B%27nai_Abraham#Russian_Shul,_1874-1891) is what is now [B'nei Abraham](https://www.phillyshul.com/history-timeline/), a Chabad {{< var shul >}} on Lombard between 5th-6th.] We heard that he was the brother of the famous {{< var chazan >}} [Pinie Minkowski](https://www.jewishvirtuallibrary.org/minkowski-pinchas), and he came from the city of {{< var bt >}}, which Jews called _Sdeh-Levan_^[This is the city's Hebrew name; it means "white fields"] and also _Schwartz-Tuma_^[This is the city's Yiddish name: "black church" (where this word for "church" has an implication of sin/ritual impurity), which is a play on words since its Ukrainian name "Bila Tserkva" means "white church"].

More than anyone else, the {{< var tumult >}}^[ruckus; again, here it is a positive connotation] was strongest from the the {{< var bt >}}ans. But also the {{< var vasil >}}ers, the {{< var rybinker >}}s, the Solovinkers, and all the other {{< var landsmen >}} who were from that general area. And when everyone went to {{< var shul >}} on {{< var shabes >}} to hear the new {{< var chazan >}}, I also went, and I really liked his {{< var daven >}}_ing_ very much. Around the same time, I actually took over a few {{< var tefilot >}}^[prayers, but can also refer to full services] from him, and then I began to sing them in my own way - both in {{< var shul >}} and at work in the shop...


But the main thing I want to tell was not that the {{< var chazan >}} gave me a few more {{< var nigunim >}} to sing, but that I saw a few people {{< var daven >}}_ing_ in the {{< var shul >}} who really caught me eye. I didn't know who they were, these people. Still, I could tell that they must be very important people - this was clear because everyone was looking around with curious glances and whispering to each other. This interested me greatly and when I asked who they were, they told me that they were actors. Yiddish actors. They had come from New York to Philadelphia to perform Yiddish theater.

They pointed them out to me one by one, and told me their names:

-- This is [ {{< var karp-full >}} ](https://www.museumoffamilyhistory.com/yt/lex/K/karp-max.htm)!

-- That is [ {{< var zilberman-full >}}](https://www.museumoffamilyhistory.com/yt/lex/Z/zilberman-moshe.htm)!

-- And this is [{{< var heine >}}](https://www.museumoffamilyhistory.com/yt/lex/H/heine-chaimovich-morris.htm)!


They were all so young and beautiful and I couldn't take my eyes off them... Here they are, the great Yiddish actors, about whom I have heard so much!... They came to hear a {{< var chazan >}}. They came into the {{< var shul >}} to {{< var daven >}} - indeed to {{< var daven >}} together with all the other Jews...

The more I looked at them, the more I was drawn to them. And when I heard afterwards among the {{< var landsmen >}} that they, the Yiddish actors who had come from New York, would play {{< var goldfaden-full >}}'s {{< var shulamith >}} here in Philadelphia^[This would have taken place _no later than_ 1887] - and indeed not just in any theater, but in the beautiful [Broad Street Theater](https://www.phillyhistory.org/photoarchive/Detail.aspx?assetId=2375) - I could not think of anything else. The first chance I got, I went to the theater, and after I managed to get past the crazed crowd that was all around them, I said to them without any other introduction:

-- Take me in, I also want to play theater.

He^[a manager, other staff - not one of the actors] smiled when he heard this. He looked me up and down from head to toe, and said:

-- Good. I'll take you in.

I thought to myself, he likes me so much that he will take me soon to the very faces of the troupe - to {{< var karp >}}, {{< var zilberman >}}, and {{< var heine >}} - and he would present me to them. They will soon give me something to do, and I will play a scene with them - just like {{< var shakhnes-full >}} the {{< var badchen >}} who was very much on my mind...

That's what I thought. And for a little while, I was really happy with this.

However, it turned out differently: It turned out, they simply needed extras for the performance, and they were looking for Jews in the community who would be eager and interested, so for this, I was hired...

Even so, I was satisfied. And when they let me out on stage for the first time^[This is {{< var sam >}}'s first performance - as an extra in {{< var shulamith >}}] alone with the "folk"^[commoner or lowly person; these are roles in the show] who were traveling to Jerusalem and singing, "_laden with all of our belongings, with walking stick in hand_", I was terrified, but at the same time I felt my heart sing inside me. I was happy. So happy, that I could not imagine any greater happiness in life, and even though I was not in the choir, I still sang with great joy:

> Laden with all of our belongings, 
>
> With walking stick in hand,
> 
> We are walking right now,
> 
> To our holy land.


Everything I saw then on the stage enchanted me and I took it all in... {{< var zilberman-full >}} in the role of {{< var avisholem >}}, {{< var karp-full >}} in the role of {{< var manoyekh >}}, [{{< var vakhtel-full >}}](https://www.museumoffamilyhistory.com/yt/lex/V/vakhtel-yosef.htm) in the role of {{< var tsing >}}^[{{< var avisholem >}}'s African servant. This role almost certainly would have been played in blackface.], and {{< var heine-full >}} in the role of {{< var natank >}}. But more than anyone else, I loved the actress who played the role of {{< var shulamith-role >}} herself...


[{{< var sara-adler >}}](https://en.wikipedia.org/wiki/Sara_Adler)^[See her Leksikon entry [here](https://www.museumoffamilyhistory.com/yt/lex/A/adler-sarah.htm)] played the role of {{< var shulamith-role >}}...

At that time she was not yet the wife of the famous actor [{{< var jacob-adler >}}](https://en.wikipedia.org/wiki/Jacob_Pavlovich_Adler)^[See his Leksikon entry [here](https://www.museumoffamilyhistory.com/yt/lex/A/adler-jacob-p.htm)], the "{{< var nesher >}}"^[This is a play on words. This _Hebrew_ phrase means "the great eagle." In German, "Adler" means eagle.] of the Yiddish stage, as he was called, but the wife of the actor and director {{< var heine-full >}}... 

And she was so young and so beautiful! And she played so well then, with so much artistic grace and charisma that I still can't forget it to this day...

Years, years, where have you flown?


