# October 12th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/10/12/01/)_ {.unnumbered}

<br>

> ^[In this memoir article, the newspaper began including brief introductions.]How I became an actor. -- My first role in {{< var goldfaden >}}'s <a href="https://en.wikipedia.org/wiki/The_Sorceress_(play)">{{< var sorceress >}}</a>^["The Sorceress", also known as {{< var bobeyachne >}}. Read a synopsis [here](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/di-kishefmakherin). This play was recently revived by the [Folksbiene](https://nytf.org/the-sorceress/) ([NYT review](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj6yNao9I6BAxUXlokEHbtYBX8QFnoECCIQAQ&url=https%3A%2F%2Fwww.nytimes.com%2F2019%2F12%2F18%2Ftheater%2Freview-the-sorceress-yiddish.html&usg=AOvVaw1rrFq-N8ca6AyZIiFJeOWI&opi=89978449)).]. -- The Yiddish theater audiences of 50 years ago.

Making the acquaintance of {{< var mogu >}} put me in such a daze that I couldn't take working in the shop at all. Everything I saw of him on stage always floated before my eyes. I remembered every movement he made, every expression that appeared on his face. His unique stage grace which really has no equal was so deeply engraved in my memory that I could never forget it. And because I was always thinking so much about {{< var mogu >}} and the show he played in Philadelphia, I started to yearn to act in the theater even more than before.

I simply wanted to begin my life as an actor. The stage cast a spell on me. But every time, when I started talking about this at home, {{< var mame >}} would cut off my wings:

-- Get this stupidity out of your head - she said. - Like we don't have enough actors in the family...^[I am not entirely confident in this translation, but I think it is roughly correct at least in terms of the sentiment. She may be referring to _her niece_ [{{< var bessie >}}](https://en.wikipedia.org/wiki/Bessie_Thomashefsky), who would have already run off with [{{< var boris >}}](https://en.wikipedia.org/wiki/Boris_Thomashefsky).]

It was difficult for me to cause {{< var mame >}} such grief; I have always behaved so that she should not suffer any shame from me. In this case, however, I could not obey her, as I had firmly made up my mind that, should there even be thunder and lightning, I must be an actor!

A short time after {{< var mogu >}} left, the actor [{{< var garten-full >}}](https://www.museumoffamilyhistory.com/yt/lex/G/gartenstein-jacob.htm) arrived in Philadelphia with a troupe. When I heard this, I was very interested and knew that I should go talk to him and convince him to give me an opportunity to play some kind of role. He was a very unique person, {{< var garten-full >}}, and it's worth mentioning some details of his biography here:

He is from Ukraine, and he came to America after the first pogroms of 1881 and 1882. He was one of the first Yiddish actors that {{< var goldfaden >}} recruited when he created the Yiddish theater. And the other actors considered him to be an educated man; He spoke very good English and he also spoke Russian, German and French. That's what they said. He was associated with the Yiddish theater for a few years and even though he was not one of the great actors, he was an innovator, and indeed a bit of a swindler, too^[Indeed, {{< var garten >}} was arrested in Philadelphia in 1888 for cheating people out of money and not paying debts.]. And when he realized he wouldn't make it big on the stage, he suddenly opened a beer saloon in Philadelphia, and it didn't go poorly. But for some reason, which he kept secret, he had to give up the beer saloon, and he left Philadelphia for Chicago.

And what did he do in Chicago?

There, he completely turned away from the Yiddish theater and began to play the role of an intellectual, of the philosopher, and he became the president of some lodge, which bore the name of the famous philosopher Spinoza, and he gave lectures. And at the same time, he got involved with politics - with American politics. And once he was even a candidate for Congress^[See Illinois 5 in [this wikipedia article](https://en.wikipedia.org/wiki/1920_United_States_House_of_Representatives_elections#Illinois). Also, it was a [contested election](https://www.amazon.com/Contested-Election-Jacob-Gartenstein-Adolph-Sabath/dp/0265117615).] and during the race he gave fiery "campaign speeches"^[קאַמפּעין–ספּיטשעס]. But he was not elected.

After the First World War, he suddenly started calling himself "Dr. {{< var garten >}}." But he was neither a doctor of medicine, nor a doctor of philosophy, nor of any other field...

And he died in Chicago. Died suddenly of a heart attack.

All around, he was a very interesting character, {{< var garten-full >}}; Fifty-sixty years ago, he was one of the pillars on which the Jewish community in America stood. When writing about the Yiddish theater of the old days, you have to mention him. And I have to mention him for myself too because of his connection to my career on the Yiddish stage in America - he gave me my first role to play in a show.

At that time, {{< var garten >}} was playing {{< var goldfaden >}}'s play {{< var sorceress >}} in Philadelphia. The troupe consisted of several distinguished people, and among them, I remember, was [{{< var vakhtel-full >}}](https://www.museumoffamilyhistory.com/yt/lex/V/vakhtel-yosef.htm)^[Recall, he was in the play {{< var shulamith >}} where {{< var sam >}} was an extra in [Chapter 6](./06_1946-10-03.qmd)], [{{< var abramovich-m-full >}}](https://www.museumoffamilyhistory.com/yt/lex/A/abramovich-max.htm), [{{< var fridman-full >}}](https://www.museumoffamilyhistory.com/yt/lex/F/fridman-feyvele.htm) and [{{< var teplitzky-full >}}](https://www.museumoffamilyhistory.com/yt/lex/T/teplitzky-mendel.htm); Like many other Yiddish theater directors who traveled around the provinces^[This term is used generally to refer to areas of the country that are outside the big cities. Think of it as, "traveled around the country."], {{< var garten >}} also relied on the fact that he would soon find enough "{{< var haimishe >}} talent"^[homegrown/local talent] among the young Jewish boys and girls who wanted to act in the theater in Philadelphia. I, too, was one of them^[And likely so was {{< var suzi >}}, his future wife; she also played with {{< var garten >}} in Philadelphia although we do not have as many details on her life.], and in {{< var sorceress >}}, he gave me the role of the young little scoundrel {{< var elyokum >}}^[the witch's servant], who twists the old witch's head and is always tricking her out of money.


When he gave a copy of the role, he told me, that I should memorize it well so that I will remember everything by heart, and as he thought that I already had experience also the stage, he did not consider it necessary to explain to me what a {{< var replik >}}^[refers to a theater cue, as in you say your line on your cue.] was. I went home and I learned the few written pages by heart, and when I came to the rehearsals, I called out all my lines at once, and I thought that I did well.

Everyone laughed, and I didn't understand why they were laughing at the fact that I knew my whole role by heart. Only when {{< var garten >}} explained to me what a {{< var replik >}} was - he told me that this was the last line someone else said and that afterwards I had to pick up the prose and speak my lines - did I begin to understand the problem. And then things went such there was no more need to laugh at me.


In general, people learned to act not before they went up on the stage, but only after they had already become a professional actor; All the talents that came to the Yiddish stage at that time were what is called {{< var samorodne >}}^[means authentic, genuine]; They didn't go to any dramatic schools, they didn't study anywhere, but they were drawn to the stage and playing theater had such an appeal for them, and they were so enchanted by it that no force in the world could turn them away from it.


At the time, my performance was highly commended, so I was told. I, too, was pleased with how I played the little con artist, who twists the old sorceress' head and cheats her out of money. I was even more pleased that, through performing the part, I realized how beautiful {{< var goldfaden >}}'s play was. I liked the whole play so much that even when I wasn't on stage, I positioned myself behind the scenes so that I wouldn't miss seeing a single scene and that I could hear the songs they sang well.

And even now everything seems alive before my eyes and I hear the singing. The butcher also comes out on the stage, a healthy young man, a man of iron, and even before he opened his mouth, everyone in the theater already knew what he will soon sing and they all know the melody very well; They know the tune because they've seen {{< var goldfaden >}}'s play more than once, and all the {{< var nigunim >}} in the play are so close to their hearts that they would listen to each song over and over again. They are very fond of these {{< var nigunim >}} and they would often sing them to themselves - at home, in the shop at work, and everywhere. They are familiar with all roles. And when they see the butcher on the stage, they nudge one another with their elbows and this meant: Soon you will hear, there will soon be a song...

And soon they indeed heard:

_Lyrics in Yiddish that are too complicated/poetic for this humble translator._


The faces of the entire audience in the theater lit up with joy. They were so pleased that they hear exactly what they wanted, and the singing continued...

_Lyrics_.

The audience in the theater knew that this is not the end of the song, but they couldn't help but applaud. And the actor who played the butcher realized that now the audience was fully engaged, and he continued to sing:

_Lyrics_.

The audience {{< var kvelled >}} and really came alive with this song. And every time when an actor on stage excelled with a song, the others in the troupe were very jealous of them, and they waited anxiously, looking forward to the moment when they would also be able to show what they could do, how they could be even better in front of the audience. And when it came to the popular song {{< var bobkelach >}}^[as in _bupkis_!], there were already people in the theater who couldn't resist the temptation and sang along:

_Lyrics_.

In singing the song {{< var bobkelach >}}, {{< var garten >}} borrowed a little poem/verse from a well-known {{< var chazan >}} in Philadelphia. And he sang it in such a way that it was really a pleasure to listen to:

_Lyrics_.


In particular after the part in the marketplace where everyone starts singing "Buy, buy customers," and then the great show become even grander, when {{< var hostmach >}} came around with his little tune:

_Lyrics_.


And after a little bit, another song:

_Lyrics_.

Together with the audience, I was so moved by the performance, both on stage and behind the curtain, that I felt like I was in seventh heaven, and when I danced so unexpectedly in the role of {{< var elyokum >}}, it wasn't because I was supposed to dance like that, but because of what was right in my heart at the time...

At that performance in Philadelphia, all of my family were there, and my {{< var mame >}} was among them. They all said that I was very good in the role of the scoundrel {{< var elyokum >}}. But I really wanted to know what my {{< var mame >}} had to say about it. And when I asked her how she liked me in the role, she just waved her hand.

-- Know what I think!... You are {{< var meshuga >}}^[crazy], that's all...

She had nothing more to say about it. Frankly, I resented this. What does it mean I'm {{< var meshuga >}}?... I played theater, showed everyone that I was an actor and she says I am {{< var meshuga >}}!


