# October 19th, 1946

> How I appeared for the first time in the ["The Kuni Lemels"](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/di-tsvey-kuni-leml)^[The play "The Two Kuni Lemels" is one of Goldfaden's most famous plays. In the 1960s, it was made into an <a href="https://en.wikipedia.org/wiki/The_Flying_Matchmaker">Israeli film</a>.]. - The actor [Jacob Frank](https://www.museumoffamilyhistory.com/yt/lex/F/frank-jacob.htm). - An offer to play in a theater in [Brownsville](https://en.wikipedia.org/wiki/Brownsville,_Brooklyn#)^[Neighborhood in Brooklyn that was _extremely_ Jewish through the 1950s.]. - Ten dollars a week^[$10 in the 1890s equates to roughly $340 today (2023)].

The whole time that I yearned to be a professional actor, I was drawn to New York. There was the center of Yiddish theater; there the greatest Jewish actors played there, and I really wanted to play with them. But at the same time that my desire to play with them in New York was so great, I was still afraid of them, but in general the city of New York did not scare me much^[Unclear if this is a correct translation - that he _wasn't_ scared of NYC.]. 

And it was no wonder that I was so frightened of them, of the famous actors of that time. There was something about them that really plunged you into fear and yet really stirred the imagination; They had a innumerable fans, who were ready to "jump into fire and water"^[implies they would do anything for them; "come hell or high water" these fans are ready to defend their actors.] for them; All the walls were covered with their pictures, and even their names were wrapped in something unusual: [Aba Schehngold](https://en.wikipedia.org/wiki/Abba_Schoengold) called himself **"Yaffa-Zahav"**^[Hebrew translated from his name: _schehn_ <-> _yaffa_ and _gold_ <-> _zahav_] - that's how he translated his name to Hebrew, so that it would sound like nice and shiny. And James P. Adler^[He was introduced in <a href="https://sjspielman.github.io/sam-kasten/chapters/06_1946-10-03.html">Chapter 6</a>.] called himself no other name than the **"Nesher HaGadol"**^[Again, another Hebrew play on words, described in Chapter 6 footnotes.] And when he used to came down with his troupe to a "province-town"^[A town outside of the major cities], a picture of an eagle with two heads was printed on his posters, along with a warning to other others who were playing in the provinces:

-- Fly away, little birds - the great eagle is here!

That was usually how the wording was...


Ah, what tales were told about the great actors and their caprices!

_Nu_, it was indeed no wonder that I was frightened to come to them in New York, even though I was really drawn there...

So, that's why I didn't go try my luck in New York after my mother's death; I instead came back to Philadelphia from the farm in Bridgeton, and there I 

That's why I didn't go to try my luck in New York, but I came back to Philadelphia from the farm in Bridgeton, and there I met the actor Jacob Frank, who then ran a barber shop. He was a very good actor, Jacob Frank, an excellent comedian, but he had no ambition in the slightest. And even more, of that, he's was pretty lazy and her never had any desire to really study a role.

In his certainty that when he goes out on the stage, everything would be fine and he would be able to "cope"^[As in, he'll just figure it out when he gets on the stage!], he neglected everything. But with his talent was able to get away with a lot of things^[This may not be a correct translation, but it's the right vibe.]. And you can say, that in a better "theater-atmosphere" Jacob Frank would certainly have been more prominent and he would certainly have occupied a more honorable place on our Jewish stage, and his talent would have developed better. 

But it was not destined for him to be in a better "theater–atmosphere." And that's how he lived out all his years, and is now completely gone from the world^[He passed away in 1942, according to his Leksikon entry, in Los Angeles where he settled when he became older and ill.] and he has been forgotten.

Together, Frank and I established a little theater company that we called the "Star Specialty Club"^[סטאַר ספּעשעלטי קלאָב]. And the manager of the club, I remember, was a young man from Philadelphia named Staller, a cigar maker, who was studying medicine and later become a doctor^[This was Max Staller, a prominent anarchist, who was also the first president of the <a href="https://en.wikipedia.org/wiki/Mount_Sinai_Hospital_(Philadelphia,_Pennsylvania)">Mount Sinai hospital in Philadelphia</a>. There is a bit more information about him on <a href="https://www.findagrave.com/memorial/33506807/max-staller">Find a Grave</a>.]

Whenever we could and wherever we were allowed, we gave concerts, staged scenes, sang, and danced. We were satisfied that we were playing theater, and we looked forward to the opportunity when we would achieve what we wanted.^[It's worth noting that, according to the book <a href="https://www.goodreads.com/book/show/2214842.Jewish_Quarter_of_Philadelphia">_Jewish Quarter of Philadelphia: A History & Guide 1881-1930_</a>, the "Star Specialty Club" troupe would sometimes play at the old fire station at 512 S 3rd St, right above South St.].

::: {layout-ncol="2"}

By chance, at that time, the anarchists turned to us with a request that we should give a benefit performance for the [_Fraye Arbeter Shtime_](https://en.wikipedia.org/wiki/Fraye_Arbeter_Shtime)^["The Free Voice of Labor"; Anarchist Yiddish newspaper], which was published out of New York. We were assured that [David Edelstadt](https://en.wikipedia.org/wiki/David_Edelstadt) himself, the editor of the _Fraye Arbeter Shtime_, will come to the performance from New York. And needless to say, when Frank and I heard about it, we were enthusiastic about it. And soon we were studying hard with all the members of our club to really learn Goldfaden's play _The Two Kuni Lemels_ well. The fake Kuni Lemel was played by Frank, and I played the real Kuni Lemel.

![Advertisement in the _Fraye Arbeter Shtime_ for the performance of _The Two Kuni Lemels_ in Philadelphia by the Star Specialty Company. The show was performed on Wednesday February 11th, 1891 in the Dramatic Hall at 5th and Gaskill. <a href="https://www.nli.org.il/en/newspapers/freiearb/1891/02/06/01/">Source</a>.](../img/newspaper_clippings/1891-02-06_freiearb.png){width="2in"}

:::

I will never forget that performance for the rest of my life. It was the first time I remember playing theater where they wrote about it afterwards in the newspaper. I was really delighted that I had already achieved such a level, even though at the same time I was afraid that Edelstein especially, _khalilah_^[God forbid], would not enjoy it.

But Edelstein did enjoy our performance in Philadelphia; he affirmed this in the speech he gave between acts of the play, and afterwards in what he wrote in the _"Fraye Arbeter Shtime"_, and with this writing he put us all in a very good mood.

For a long time, we went through such _tumult_ in the "Star Specialty Club" of ours, and it didn't really matter to us that we didn't have much luck. The point was that we had the opportunity to play theater, and we even had our own fans, just like the stars in New York. And that alone is no small thing.

Among our fans, I recall, there was one named Herman. He was working as a cloak-operator, "Columbus' craftsman," as those who took up tailoring in America were called at that time^[a very common profession in the new world!]. And he, Herman, was a strong supporter^[big fan] of Frank's, and since he was a bit of a _dreykop_^[Literally "spinning head," an idiom that refers to a schemer/swindler. They talk so much they spin your head around.] he already had a plan that he would grab Frank, and with him [Frank], leave for Baltimore, because he [Herman] had a lot of relatives and _landslayt_^[aka, _landsmen_ - people from the same region in the old country] there. And he was sure, that there they would accomplish lots of great things, and they will both make golden business^[An aside: In the musical _Man of La Mancha_, "The Barber's Song" includes the line, "Thou and I now, ere I die now, will make _golden history_!" <a href="https://en.wikipedia.org/wiki/Irving_Jacobson">Irving Jacobson</a>, a famous Yiddish theater actor/director, originated in the role of Sancho. The lyricist was Joe Darion, who at least at some point worked in <a href="https://archives.nypl.org/the/18848">the Yiddish arts</a>. In conclusion, _Man of La Mancha_ is, indeed, the Yiddish theater.] with the theater. 


I am describing all these details here simply because, I believe, that it is worth getting knowing about, in order to have an sense of those types who hung around the theater, and how such chaos and such maymen ruled the Yiddish theater in the "provincial cities"^[not New York]. 

Of all the dreams that Herman had when he grabbed Frank and took him from Philadelphia to Baltimore, nothing came of it. The Jews in Baltimore could not be taken by storm, as Herman had originally imagined. And on top of that, Frank "played a trick" on him and in Baltimore, he fell in love with a beautiful girl, and in his love his head was so twisted that playing theater was no hardly in his mind at all...

But Herman didn't give up. He had long decided that he must accomplish something in the Yiddish theater and show what he is capable of. And when he came back to Philadelphia from Baltimore "with Baytshel,"^[means, "came back empty-handed"] as we used to say in Ukraine, he teamed up with a certain "sign-painter," whose name was Shapiro. He, Shapiro, was also a great lover of Yiddish theater, and in addition just as much of a _dreykop_ as Herman, and he didn't have any plans anyways. But soon he a plan for me:

-- You want, we should all go in together?^[I've rephrased from an idiom that doesn't translate well] - he says to me,  -- You want New Yorkers to start talking about you and the earth will quake for you^[I changed this from "tumult in the world for you". It's a conversational idiom - implies, you want to be famous in NYC?!], ah?... Are you coming with us to Brownsville?!

-- What's in Brownsville? -  I asked.

-- What do you mean, "What's in Brownsville?"?! - Shapiro said excitedly to me as if he were about to curse me. - You don't know what Brownsville is? Brownsville is a growing Jewish city, people are building it up, and the Jews will delight in having a Yiddish theater. You will be carried around proudly on your head^[Almost certainly idiom for "they will love you"]...

He did not have the slightest doubt that this would indeed be the case. And so that there would be no doubt for me either, he continued to reply to show that besides just the fantasy, there was something tangible/real too.

-- First of all, - he said, - 


you need to know that when it comes to a theater, where to play, you don't have to turn your head. There is a Jew in Bronzeville, whose name is Parmer, and he has built a casino, which is truly unique in the world. He built his casino on Pitkin Avenue, and that in itself is no longer a luxury. Let's talk about something - Pitkin Avenue!... It's gone once. And now listen further: You will get ten dollars a week!
When I heard this, I did not believe my own ears.
- Ten dollars a week...!
I really didn't expect such happiness then, and it occurred to me that it was nothing else but that it simply fell from heaven for me.



