# October 24th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/10/24/01/)_ {.unnumbered}

<br>

> I play theater in the Brownsville of old times. -- It starts well and ends poorly. - My wedding. -- I sell my farm to [Israel Weinblatt](https://www.museumoffamilyhistory.com/yt/lex/W/weinblatt-israel.htm).

This was still in those times when in Brownsville, {{< var yiddishkeit >}}^[Yiddish/Jewish culture] was felt at every turn. And even more than during the week, you could feel it on {{< var shabes >}}^[Shabbat]. The shuls were packed. Jews went to pray, and just like in the shtetl in the old country, they took the children with them. And walking to the shul, they dressed up for {{< var shabes >}} and put on the tall black top hats on their heads, and in the street they all gave one another a {{< var gut-shabes >}} and we everyone lived together as one big {{< var mishpucha >}} who suddenly felt the good taste of what it is like for Jews to live in a free country where you don't have to be afraid of anyone and where you can walk around the streets with your head held high. 

There in Brownsville, it wouldn't occur to even the greatest [{{< var apikoros >}}](https://en.wikipedia.org/wiki/Epikoros)^[heretic] to do such a thing as light a cigarette on {{< var shabes >}} in the middle of the street; He would be afraid to do such a thing, or people would shame him for doing it.

And everywhere, wherever we walked and wherever we stood, we saw how they were building and building; Everyone bought lots, everyone had plans, and whoever was able to undertake it, was drawn into the momentum of building the city, which later became one of the greatest Jewish cities in the world^[Recall, in 1946 when Sam was writing this, Brownsville was still 100% Jewish]. 

Everyone in Brownsville spoke amiably about the mud and filth^[This is not likely a correct translation, at all. Yiddish: די ציגען און די בלאָטעם]. People did not complain about it. They were not ashamed of it. And in that alone there was also a characteristic {{< var haimishe >}} comfort.

Everything in Brownsville at that time had a genuine Yiddish style, and when you walked down the street and heard people speaking their own {{< var haimishe >}} kind of Yiddish, you could recognize who came from where and you already knew who was who - Who is a Litvak, who is a Galicianer, who comes from Poland, and who from Ukraine^[These regions all have different Yiddish dialects. Litvaks are Lithuanian/northeastern, and Galicianers are from the Galicia region, which is now part of Poland and western Ukraine]. 

And from the open windows of the houses, songs spread through the air - popular songs from the Yiddish theater, or Yiddish folk songs of all kinds. And here and there someone would even try out the _kehele_^[I can't find what song he is referring to: קעהלע] and he sang {{< var chazanishe >}} chants and would trill, simply for his own enjoyment, so that he would feel at home/at ease in America...

Such a city was of course fit for a Yiddish theater. I was sure of this. Naturally, I immediately got to work, and the first play that we played there was {{< var boris >}}'s {{< var alilesdam-full >}}.  That's what the play was called; One name for a play was not enough, and therefore people usually added an "or" well... 

After that we played another play, indeed again with an "or," as the style was: {{< var velvel >}} was the name of that play, and it was adapted by {{< var thomash >}}^[Boris wrote this based on a play written previously by [Shimon Beckerman](https://www.museumoffamilyhistory.com/yt/lex/B/bekerman-simeon.htm).].

About such a thing as getting permission to play a play, there was very little concern. On top of that, I was already in touch with {{< var thomash >}} because his wife Bessie and I were relatives,^[They are cousins, and almost certainly they are first cousins - I believe their mothers were sisters] and {{< var thomash >}} himself already knew me well and he got along very well with me^[Recall, they had also acted together in Philadelphia for the summer of probably 1888 or 1889].

The first couple of weeks in Brownsville didn't go badly, and I got exactly my salary - ten dollars a week. But after that it started to get worse and worse, until it became so bad that we received no salary and couldn't pay rent anymore. 

It was bad for me then, very bad. And in the moments when I was miserable and I was looking for a way to improve my dark fate, I used to spend time with the actors of the other troupe who were, at that time, playing in another casino in Brownsville^[Probably Singer Hall]. And during that time I became close friends with the actor [{{< var charlie-full >}}](https://www.museumoffamilyhistory.com/yt/lex/C/cohan-charlie.htm)^[Sam and Charlie later became very close friends. Along with Sam's son Louis, Charlie was with Sam when he passed away. There are conflicting historical records about whether Sam actually met Charlie at this time. On one hand, records show that Charlie was born in 1886, and these events are taking place in 1893-94 when Charlie was still a child living in the Lower East Side (as confirmed by Charlie's [obituary in the {{< var forverts >}}](https://www.nli.org.il/en/newspapers/frw/1973/09/25/01/article/49/?e=-------en-20--1--img-txIN%7ctxTI--------------1)). On the other hand, Sholem Perlmutter [described](https://archive.org/details/nybc209311/page/n286/mode/1up) that Charlie did indeed act in Brownsville in Singer Hall at the same time as Sam did.], who is now the Secretary-Treasurer of the [{{< var hau >}}](https://en.wikipedia.org/wiki/Hebrew_Actors%27_Union), and also with [{{< var s-weintraub >}}](https://www.museumoffamilyhistory.com/yt/lex/W/weintraub-sigmund.htm), who was not only a very good actor, but also a decent person, and moreover very smart and had a fine sense of humor.

We were all still young then, full of life; We could even make fun of our own troubles; I didn't allow myself any very big and heavy worries, and it was therefore a completely natural thing, that in such a time, when things were so bad and I wasn't receiving a salary, it should occur to me, that now is precisely the right time to get married...^[In fact, as we know from [an article Sam wrote in the {{< var forverts >}} in 1913](https://www.nli.org.il/en/newspapers/frw/1913/05/04/01/article/21/?e=-------en-20--1--img-txIN%7ctxTI--------------1), his friend {{< var frank >}} suggested to him that if he's going to starve to death eating a piece of bread a day, he might as well get married first.]

Thought and done - I got married to the charming dark-haired girl {{< var suzi >}}, with whom I was so deeply in love.

And we held the wedding in our own way - with a benefit performance^[implying all proceeds go to support them] at Parmer's Casino. And all in all, the benefit brought in about thirty-five dollars. And after the religious ceremony, we had bread with herring and drank a little real liquor and it was lively and joyous.

I didn't know myself what would happen next. I relied on miracles, and - a miracle really did happen...

The miracle was that well-known actor {{< var weinb-full >}}, one of the first pioneers on the Jewish stage, told me that he wanted to buy my farm from me; He decided, he said, to become an actor, but it would be better for him to be a farmer, and his greatest dream was that his children would also be farmers; He doesn't want them to be actors...

{{< var weinb-full >}} resolved to become a farmer because he had been sidelined by theater politics and no longer stood out^[Not a leading man anymore]. This greatly angered him; He felt very offended by this, because earlier he was loved by the public and he excelled in such roles as Shmerke the servant in {{< var shomer >}}'s {{< var coquettes >}}, {{< var kalman-kroch >}} in [Yitzhak Yoel Linetsky](https://en.wikipedia.org/wiki/Yitzkhok_Yoel_Linetzky)'s {{< var yingl >}}, and {{< var hostmach >}} in {{< var goldfaden-full >}}'s {{< var bobeyachne >}}. He excelled in other roles as well, and he could not forget that. And because it hurt him so much that he was pushed into a corner and no longer given the opportunities on the stage that were given to him before, it seemed to him that he no longer had anything left to do there, and that the best thing for him would be to become a farmer...

-- You, Kestin, - he said to me - you left the farm to become an actor, and I go there to become a former actor...

{{< var weinb-full >}} paid me five hundred dollars in cash for the farm, and as soon as he settled there, he set to work diligently. And I remember how once, when I came to him in the afternoon and met him while he was working in the field, he told me with a smile that his son Charlie - the same Charlie who years later became the well-known lawyer for the theater - is still sleeping and the work on the farm is not on his mind at all...

-- You see, Kestin, - the old {{< var weinb-full >}} said to me in a joking way tone - you see, he doesn't have to work. But I am an orphan, without a father or a mother, so I have to work. There is no other choice...

Above all, {{< var weinb-full >}} was always ready with a joke. Even when his heart was heavy, he could still make jokes, and it was not difficult to see that even though he left the stage, he wanted to return to it. And he tried several times to make a comeback, but it never worked out for him.

By the way, around that time {{< var marx-full >}} also left the Yiddish stage, and when he finished studying law, he became a lawyer, and it was said that he used to say: "Better this way; I'm not going to be {{< var mogu >}}"...

The five hundred dollars that {{< var weinb-full >}} gave me for the farm really opened my eyes. I immediately assembled a troupe in Brownsville, and I went to Newark to play Yiddish theater and before I knew it, I had laid down two hundred dollars there and I already became a lesser^[presumably meaning "poorer"] man. But it didn’t work out and I went with my troupe to play in Passaic, and from Passaic - to Bridgeport. And when I came back to Brownsville, there was nothing left of the five hundred dollars and I was left without a penny.

In general, Yiddish actors suffered a lot at that time, and this further exacerbated the chaos and confusion, which was already so pervasive in our miserable theater-atmosphere. Everyone wandered around lost, everything happened by chance and you couldn't know what tomorrow would bring and what paths you would take...

Everyone did what they wanted or whatever occurred to them^[In other words, there are no rules]. And the greatest chaos, as I have already said, reigned in those troops who also played in the provinces...

Right then, when I came back to Brownsville, without a cent to my name, it was nearly {{< var pesach >}}. {{< var Nu >}}, I was sure that during {{< var pesach >}}, the people of Brownsville would come to Parmer's Casino to see Yiddish theater. How else?^[What else would they do?] And I expected we would have great luck and I made all the plans. But no one came to the first performance that we announced. Really, no one. Not a single Jew... No one came to the second performance either...

And the same thing happened in the casino, where {{< var charlie-full >}} and {{< var s-weintraub >}} played. No one went there on the {{< var yontif >}} either...

It was just as though everyone had discussed it among themselves and agreed not to go...

My heart was heavy at that time. And I kept thinking about one question: What will happen next? What, after all, will it be...?







