# October 26th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/10/26/01/)_ {.unnumbered}

<br>

> {{< var thomash >}} and {{< var karp >}} come to my aid in Brownsville. -- **{{< var mogu >}}'s** renowned song {{< var minha >}}^[מן המצר; This song title is derived from [Pslam 118](https://www.myjewishlearning.com/article/min-ha-meitzar-calling-to-god-from-the-depths/).]

The whole {{< var pesach >}} {{< var yontif >}} came and went, and not a single Jew came to our theater. And after the {{< var yontif >}} was over, we came up with a new idea for how to attract the Jewish community of Brownsville to come to our performances in Parmer's Casino: we let it be known that we would play theater for free...

Yes, for free. No one will have to pay any money for a ticket. You won't even need a ticket at all. The only thing you will need is - come to drink beer and pay for it, and then you will enter from the saloon into the main hall where the theater is, sit down wherever you can get a spot, and there you'll see a performance.

This, the public in Brownsville was interested in, and they started coming to drink beer and actually see a Yiddish show along with it. Then the casino was able to pay my salary, and I started to earn a little bit of money. But really only a little. We didn't have much luck.

That's how Yiddish theater was in Brownsville in those days. And when a Jew wanted to see a proper performance, he usually would go to New York^[Lower East Side] where "the bears," the famous actors of the Yiddish stage, played.

Around that time my wife gave birth to our first child^[Their first son Freddie was born in 1894. He would later go on to fight in WWI, during which he was exposed to mustard gas and was chronically ill with severe lung problems for the rest of his life, until he passed away in 1935 from associated complications. He worked in the theater box offices and similar before he passed.], and I my situation was such that only God alone could take pity on me. If it weren't for the few fans I had in Brownsville, my situation would certainly have been much worse. My fans, simple but good and kind people, helped me out with whatever they could. But they couldn't do much for me, because they themselves were also very poor and they also toiled hard for a piece of bread.

So what could I do? I went to {{< var thomash >}} and asked him to save me.

-- You have to do something for me - I said to him - as a member of the family, you have to help me out. Don't forget that I am now a father of a child, and there are times when I simply have no bread at home...

It was difficult for me to speak like that, because that was not at all my nature, but I had no other choice.

And {{< var thomash >}} promised me that he would come to Brownsville to play a show at Parmer's Casino especially for me, and all the proceeds would go to me.

{{< var Nu >}}, I was certainly very pleased with this. And I was even more pleased that he chose to play the piece [{{< var esther-eingedi >}}](https://jewishmuseummd.pastperfectonline.com/Archive/B9E9D9B4-EFFD-45A8-A2A7-069980106953)^[[Eid-Gedi](https://en.wikipedia.org/wiki/Ein_Gedi) is an ancient spring in Israel] for the evening performance. This was one of the most popular plays among Jews at that time, and I was sure that people would be packed in the casino like sardines, and there would be a lot of proceeds.

As he was wont to do, {{< var thomash >}} also brought his bravado and his "actor's caprices;" he ordered everything to be prepared so that nothing would go wrong, and he also had all the decorations for the production of the play {{< var esther-eingedi >}} brought in from New York.

And if {{< var thomash >}} wants it, you must obey...

This ended up costing a lot of money even before the night of the performance. And when it came to the performance, the early proceeds were not much, because most of the Jews of Brownsville had already seen {{< var thomash >}} play {{< var esther-eingedi >}} in New York. They didn't want to see him in the same play again. And in the end, when we counted all the proceeds, all in all the performance only brought in something like $12...

In desperation, I then turned to the actor {{< var karp-full >}}, who then, just like {{< var thomash >}}, had a big name, and the audiences really loved to hear him sing. He actually had a very pleasant voice, the actor {{< var karp-full >}}, and his voice had a distinct appeal to it. In addition, he had a fine posture and the kind of good affect that usually makes an impression on an audience. It turned out that he would come to Brownsville especially for my sake to attract an audience to a performance; We would play the piece {{< var haim >}}, and he, {{< var karp-full >}}, would sing between the acts.


This saved me from all my troubles. When the people in Brownsville heard that {{< var karp-full >}} was going to sing, they gladly came to Parmer's Casino to hear him, and the most interesting thing about it was that they wanted to hear exactly the songs that they had already heard him sing before...

It turns out, it's not the same with singing as it is with a play; when it comes to singing, you can listen to something you enjoy many times, and the closer a song is to your heart, the more you want to hear it still...

Even to this day, I can't forget the enthusiasm he was met with when he went out on stage to sing and what an ovation he received after he sang the first song:

> Oh, how much longer, great Lord,
>
> Will your people be in {{< var goles >}}^[diaspora/exile; this is a hebrew word: גלות]?


And the enthusiasm grew even greater when he began to sing {{< var mogu >}}'s song {{< var minha >}}^[[Sing along](https://search.library.wisc.edu/digital/ABARUZMQH2BDSK8K/A5KJ5U2YG7YEYK8R)!], which was very popular at the time:


> מן המצר קראתי יה
>
> ענני במרחב יה
>
> וואס קענסטו, מענסטעלע,
>
> מיר גאר טאָן
>
> פון אייביק אָן.
>
> איך לאַך פון דיר
>
> ווען גאָט איז מיט מיר


Like all the songs that {{< var mogu >}} wrote during the years he wrote for the Yiddish stage^[my translation; {{< var sam >}} wrote {{< var mogu >}} "created for" the Yiddish stage], his song {{< var minha >}}, also had a meaning; it evoked feelings and memories. And his creations had a genuine Jewishness to them, his is still authentically Yiddish both in their subject and in their melody. And {{< var karp-full >}} knew how to bring this out, and when he sang {{< var mogu >}}'s {{< var minha >}} again, the crowd echoed every word:

> דאס יידעלע, אים קענען אלע
>
> !קליין און שוואַך וואס איז ער גאר
>
> דאַן שפּילט ער די גרעסע ראָלע
>
> שוין זייט פילע טויזענט יאָר.
>
> שונאים האבען שוין אָהן א צאָל
>
> צו דערשטיקען אים פּרובירט,
>
> דאָך באגראָבען זיי האט ישראל
>
> און ער לעבט און עפויסטירט.


And then the singing went in the form of a question and an answer:

> וואס איהם פארשאפט
>
> האס אזא קראפט.
>
> ווייל שטענדיג איין ליד
>
> זינגט דער איד:
>
> מן המצר קראתי יה,
>
> ענני במרחב יה,
>
> ענני במרחב יה!
>
> וואס קענסטו, מענסטעלע,
>
> מיר גאר טאָן
>
> פון אייביק אָן.
>
> איך לאַך פון דיר
>
> ווען גאָט איז מיט מיר

Nowadays, no one remembers the song {{< var minha >}}, but in those times I'm telling about here, this song was famous to and beloved by Jews, and this was not for no reason; the sang was not only about the {{< var tsures >}} the Jews endured, but also about Jewish hopes, and it reminded you of what you were once taught in {{< var heder >}}. Next, the song next went like this:

> פרעה האט פיר הונדערט יאָר
>
> געבאַדען זיך אין יידיש בלוט,
>
> איינגעשפאַרט האט ער זיך נאָר
>
> אונז חויילאזען וויל ער גיט!
>
> נו, וואס האט ער געהאט? מכות בכורות
>
> און אין געבליבען צו געשפעט,
>
> און ישראל דערציילט דאס היינט לדור דורות
>
> פּסח אויף דעם הסב–בעט.


And here comes the song again in the form of a question and answer:


> וואס איהם פארשאפט
>
> האס אזא קראפט.
>
> ווייל שטענדיג איין ליד
>
> זינגט דער איד:
>
> מן המצר א. אז. וו.

The story about the miracle of {{< var purim >}} is not left out in that song, and this part was sung so that Jews would remember that they outlived all their bitter enemies:

> אונז אמאָל האט געוואַלט דערשטיקען
>
> דער בייזער המן, אזוי א פּלאָג!
>
> יידישע גערגעלאך נאר אויסכיקען
>
> אלע, נעבאך, אין איין טאַג.
>
> א סוף האט ער געהאַט, דער עמלק,
>
> געהאנגען האט מען אים אָהן רעש,
>
> א יאָהרצייט האט נאָך אים יעצט ישראלי׳ק
>
> און פארבייסט א המן–טאַש.

And then the "וואס איהם פארשאפט האס אזא קראפט" part comes again, and so on.


Jews really loved this song. It was sung everywhere. And it's no wonder that {{< var karp-full >}} took it very seriously when he sang it at my benefit performance in Brownsville between acts.

And on top of this, the financial success from it was also great - the event brought me $150, and that saved me...

But I couldn't stay in Brownsville any longer. It was clear to me that there was no luck for me there and I started thinking about where I should go and try my luck in what kind of state I should settle in. America is large. There are many states in the country. But what kind of state should I go to?
