# November 7th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/11/07/01/)_ {.unnumbered}

<br>

> The fire in the Yiddish theater in Baltimore in which 22 people were killed. - The comedian Tanzman who could not dance^[This is a pun - Tanzman means "dance man."].

In the operetta "Meilitz Yosher" that we were playing in Boston, the character I played was sent to prison and put in shackles, and from there I sang the song ["The Moral."](https://www.loc.gov/resource/ihas.200185539.0)^[I suspect there is a particular Yiddish connotation to the world "moral"]

> ^[Translation by me, with (?) indicating lines I'm very unsure of.] The moral remembers for a long time
>
> It leaves trace upon trace,
>
> Though in every place and case,
>
> It has a different face.
>
> Lying imprisoned, tied down
>
> in long, countless chains.
>
> (?) Suddenly from the prison cell's wall
>
> (?) will freedom ever come once more.
> 
> And when you sees the tracks
>
> from the chains all around,
>
> Oh, it will lie in your memory, 
>
> the iron moral.
>
> Yes, the moral, the moral, 
>
> Does good everywhere.


Singing alone was not enough for me, so on top of that I also - of my own accord - did a dance after as well, and I danced in the chains, and this was a big hit with the audience, and I therefore received a lot of applause at each performance. .

The audience was just simply pleased when I danced in chains...

Tanzman also played the same role; we were both offered the same role in "Meilitz Yosher." And since Tanzman could not dance at all, he he did not excel as much as I did in the role, and this made him very resentful and he urged me not to dance in the role either.

-- What is this dancing right in the middle of the scene? - he scolded me. - There's no need to dance. No one is expecting you to dance!...

But I was firm and obstinate:

-- It will do you no good, even if you stand on the roof^[This phrase is likely religious in origin - when the Messiah comes, he will "stand on the roof of the Temple." Sam saying:, even if you were the messiah telling me to stop dancing, it would be to no avail.]; I can dance, so I dance. If you could dance, you would certainly dance too...

We often fought over this and Abba Schoengold always had to work to make peace between us. And when the operetta _Meilitz Yosher_ was taken down from the stage and we started playing other pieces, the business in Boston did not go so well, and then [Madame Keni Lipzin](https://en.wikipedia.org/wiki/Keni_Liptzin)^[Read her [Leksikon entry here](https://www.museumoffamilyhistory.com/yt/lex/L/lipzin-keni.htm)] was brought down from New York to rescue the situation. She appeared in "The Bowery Tramp"^[A play written by Rudolph Marks], in "The Lost Soul,"^[Recall Sam was in this play in [Chapter 14](14_1946-11-02.qmd)], and "Rachel and Leah"^[I can't find this play. It's rather hard to google...], and that did help a little, but really only a little, not much. Soon it became bad again and we couldn't pull through. It just wasn't working.

In those times, [Morris Winchevsky](https://en.wikipedia.org/wiki/Morris_Winchevsky) published a weekly newspaper called _Der Emes_^[means "the truth"]. He was the editor of the newspaper. And I remember once, when right before they raise the curtains to play some piece whose name I no longer remember, we were informed that Winchevsky himself was coming to the performance and then Abba Schoengold announced that today we should "play in such a way that there should be smoke."

We all wanted to impress Winchevsky with our acting and because of that we really applied ourselves and tried hard. And as it seems, he was very pleased with us; The best proof of this was what he later wrote about us in _Der Emes_, and in this article he also wrote good things about me, that I am a talented comedian and that audience found my acting to be very strong^[This [article published December 6th 1895 in the Boston paper _Der Emes_](https://www.nli.org.il/en/newspapers/emet/1895/12/06/01/article/10/) announces that Keni Lipzin is playing in Boston, in particular playing in "The Lost Soul." Sam, among other troupe members, are also mentioned in the article. This may be the article that Sam is referring to, but I have not translated it. Regardless, this article tells us these events are taking place in late 1895.]


What Winchevsky's wrote about us really encouraged us. We were all very excited by it. But it didn't bring large crowds to the theater. There was never any income. And when we saw that it was bad, we left Boston and went to Baltimore, and there Abba Schoengold was in charge again, not Tanzman. He appeared in [Jacob Gordin](https://en.wikipedia.org/wiki/Jacob_Gordin)'s ["Yiddish King Lear"](https://en.wikipedia.org/wiki/The_Yiddish_King_Lear) and also in "Crown Prince of Jerusalem"^[This was written by Joseph Lateiner], and it went so well that it had never been better.

Schoengold was in seventh heaven, and as his manner was always, he lived in such a way that he was always spending all his money^[Sam writes something that doesn't quite translate: money was "bankrupting" between his fingers], and in the restaurants where he ate, you knew that no matter how much food was brought to the table, it was never enough and he wanted more and more...

There was seldom a performance that the theater where we played wasn't packed and people didn't have to stand "head to head." The Jewish community in Baltimore then really "ate Yiddish theater with bread"^[an idiom that I think means really consumed it regularly/daily]. And based on this, we didn't think at all about traveling to another city; We were sure that we would even play there not only for one season, but maybe for several seasons, and we already had all the plans for this and Abba Schoengold saw to it that people in New York knew about it and that all the famous actors there would spread the word so that they would once and for all have to admit that we, those who play in the provinces, are not insignificant or weak, and we could also "conquer a world." 

It was really good for us then, and we were happy that we took Baltimore "by storm."


---

But during one of the performances, a gas pipe was lit and when the flame gave a blow with a crack, someone was so frightened that he started shouting 'fire' at the top of his lungs! And then there was such a panic in the theater that it was impossible to calm down; The startled crowd was so lost that, pushing towards the floor and pushing each other, they didn't look back when someone fell; In an effort to save themselves, people trampled on those who had fallen. And in the end, after the panic had barely subsided and the theater was already empty and everyone was already outside, it turned out that twenty-two people had died in the stampede…


