# November 11th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/11/09/01/)_ {.unnumbered}

## CHAPTER IN PROGRESS

<br>

> The frequent quarrels among Yiddish actors of old. - They used to fight over their source of income, over roles, and even more over love^[as in, love affairs]. - A quarrel between the actors {{< var schoen >}} and Tanzman, because of Mrs. Tanzman's role.

Together with {{< var frank >}} and with {{< var jakele-full >}}, I {{< var schlepped >}} around the provinces and it was, as they say, all ups and downs - here it was good and there it, and it turned out like in Pharaoh's dream: [The seven lean cows ate the seven fat cows](https://en.wikipedia.org/wiki/Joseph_(Genesis)#Joseph_in_prison), and you were always twisting your head wondering what would come next.

Oftentimes it was like this - we would arrived in a city just when, only a few days earlier, another wandering troupe had just departed, and they had just "skimmed the top off" so there was nothing left for us. Sometimes, just as we arrived in a city, we would meet another wandering Yiddish troupe who was playing the same plays that we had chosen to play.

In general, there was terrible and fearful confusion; People tripped over each other's feet, bumped into each other's heads, and everyone got in one another's way.

In many cities, {{< var jakele-full >}} displayed his resourcefulness to get us out of an unpleasant situation, and on a regular basis, an ingenious idea would strike him, and it was really something astonishing. The main thing was - as bad as it got, he didn't give up and he always encouraged us. Even when he himself had "no {{< var yontif >}}_'dige_ in his heart"^[no sense of joy or festivity], he nonetheless was still able to pass the time reading Shakespeare's _Halmet_ for the umpteenth time, always exclaiming with enthusiasm:

-- I say, {{< var chevreh >}}^[Here, this means "dear friends"], this is a _play_ - a rare thing in this world!

He was always reading plays. Printed and also hand-written. And he had a such good memory, that it was enough for him to just see a play on the stage once or twice, and he already had memorized it...

On top of this, he also always dressed very nicely and elegantly, and I liked that very much about him, because I always liked to dress nicely and elegantly. And {{< var jakele-full >}} always behaved like a real cavalier who really attracted the ladies...

While wandering from city to city, we never arrived anywhere prepared; No one expected us anywhere and no one was eagerly awaiting our arrival. We just wandered, in demand or not. Sometimes you found yourself in a good spot, or sometimes you didn't and it was bad, and in those times it was really miserable and gloomy. And once, when we arrived in Cleveland, we were straight away given some good news - the troupe of {{< var abba-full >}} and Mr. and Mrs. Tanzman was already playing here. The same troupe that I left after fighting with Tanzman.

I mention this, because from what I am going to tell you, you will be able to get a sense of the atmosphere that then reigned in our theater circles, and all in all it was very characteristic of all the chaos of that era.


It was necessary for one of us to meet with Tanzman and talk with him about what could be done so that we could also make something out of being in Cleveland, and so that we could at least continue to cover our expenses. And it was decided that {{< var frank >}} should to go to Tanzman. I could not go to Tanzman because we had fought.

So {{< var frank >}} went to him and he didn't come back...

He stayed with Tanzman's troupe and and played with them there, and where were left neither here nor there^[with nowhere to turn, stuck], so {{< var jakele-full >}} also left and I was left alone and exposed and there was nothing I could do.

That's how Tanzman got even with me for the fight we had had before in Baltimore. He could not forget about it, and he could not let go of his anger towards me until he got his revenge.


In general, Yiddish actors in the troupes at that time fought a little too much, not only about income and about roles, but also about various other kinds of things; Morale was not at all high, and when an actor had a jealous wife, or an actress had a jealous husband, tempestuous and boisterous scenes often played out, and everyone had something to talk about and someone to gossip about; Everyone was talking about some kind of episode, and it was nothing new for someone to steal another's wife or husband. And when such a thing happened, the whole troupe was thrown into such a {{< var tumult >}} over it, and they all cast the blame at one another sins at each other, and it was such a mess...

It was no wonder it was like this. After all, actors are no more than real people, with all their virtues and with all their flaws, and God knows, that everyone, in all circles, endured these things^[This sentence like has some translation errors, but the meaning is definitely preserved. I omitted phrases that were too challenging for me to translate.]. But when something like this happened between actors, it was always a different story, because they, they actors, were a close-knit circle and the "highly respected audience" always had their eyes on them - not only when they were on stage, but also in life. People always saw the life of an actor as though it were a mirror, and whenever something happened to him, even when it was a personal matter^[This could be wrong; the correct phrase might be "commonplace/familiar occurrence"], people would straight away shout it from the root tops and talk about it everywhere, in all the circles where people delighted in gossip and slander...

In telling this, I am not trying to tell about the not-so-noble morality that prevailed among actors in those times. I just wanted to mention this fact as one of the reasons that, many times, fights became so bad that troupes split into two, and then they would compete with each other and people were ready to draw daggers.

On this topic alone, people could really tell a lot of very interesting things, but it is better to talk about it less than one could, and apart from this I believe that I am not the kind of man who speaks ill of others^[This is my translation. Sam writes something along the lines of "a man who must look for sin on others," which is perhaps an idiom, but I believe my translation captures his meaning.]...

Many of the things that people did in those times now seem foolish, when you come to old age and take stock of your life that has gone by. And who knows^[This _might_ be an idiom, "And God knows!"]? Maybe if a miracle happened and you became young again, you might do the same foolish things all over again, even if you had the full awareness that all those things are nothing more than foolishness and they aren't worth all the fuss that people make them out to be...

But I don't want to get more into philosophies of life here, so I will get back to that I was previously talking about regarding my situation in Cleveland:

From what I heard about what was going on in their troupe, it was clear that, between {{< var schoen >}} and Tanzman, they could not the keep peace in the troupe; People were fighting over roles and also about the fact that Tanzman wanted his wife, the prima donna, to be featured more than everyone else in every play they performed.

He was always anxious about his wife, and no matter how much he did for her in the theater, it always seemed to him that it was still not enough and that he had to do more and more for her; he loved her very much, even though you could hardly say that she was beautiful. He was always under the illusion that everyone was going to fall in love with her, and he was full of fear that she would not stay with him. And in the end, she actually was taken away from him and it completely ruined his life.

{{< var abba-full >}} could not tolerate that Tanzman was spinning things like this, so that his wife, the prima donna {{< var berta >}}, would be more prominent than all the others in the troupe. {{< var schoen >}} wanted to be featured too, and he was sure that it would be better for business in the theater, because he had a bigger name and was more popular with the audience. And they fought over this for so long, until {{< var abba-full >}} became angry and left the troupe completely.

-- He will come back to me to get me to play with him again! - fumed {{< var schoen >}}. - He'll see how well the troupe does without {{< var schoen >}}!...

He though of himself very highly, the actor {{< var schoen >}}. And he really was a very good actor and it was a real pleasure to see him in the roles he played.

After the fight with the Tanzmans, {{< var schoen >}} left Cleveland for Pittsburg, and there he hastily put together a troupe and began playing. And as he always thought highly of me, and on top of that he knew that I was the kind of man who you could get along with and doesn't pick fights with everyone, he called me out of Cleveland a week later to come to Pittsburgh, and there we began a totally new "marriage"^[partnership], and it was good again.
