# November 14th, 1946

##### _Link to [{{< var forverts >}} edition](https://www.nli.org.il/en/newspapers/frw/1946/11/14/01/)_ {.unnumbered}

> When I played {{< var shabtai-golem >}} in {{< var lateiner >}}'s {{< var lostsoul >}}. -- The two popular songs {{< var wiseson >}} and {{< var purim-nes >}}.


As in every city, in Pittsburgh we also had a group of very {{< var voyle-yiden >}}^["good/happy/nice Jews"] who were there for us and were ready to do anything for us, simply because they loved Yiddish theater and enjoyed that they could somehow be of help to the traveling Yiddish actors.

These {{< var voyle-yiden >}}, who in their simplicity had a lot of {{< var haimishkeit >}}, were then in all the cities and towns of America, and {{< var abba-full >}} was able to find them everywhere he went. And he didn't only need them because they were well-connected and he could hitch his wagon to them to sell tickets for the show, but also because they could find some kind of home for his children and would take care of them while he was busy acting. 

At that time, the actor {{< var abba-full >}} became a widower^[His wife was [Clara {{< var schoen >}}](https://www.museumoffamilyhistory.com/yt/lex/S/shoengold-clara.htm)]. His children were still small then. His son Joe^[His Leksikon entry has not yet been translated, but it is available from Volume 6, page 5344.], who years later became a well-known actor and married {{< var adler >}}'s daughter [Frances](https://www.museumoffamilyhistory.com/yt/lex/A/adler-frances.htm)^[One of {{< var jacob-adler >}} and {{< var sara-adler >}}'s children], was just a little boy then. And since {{< var abba-full >}} loved his children very much and he was extraordinarily loyal and devoted to them, he took them with him everywhere he traveled to play, and people knew that the first thing he did when he arrived somewhere in a city was find a home for his children in a respectable household where they would be well looked after. And he usually found such a home with the help of one of those {{< var voyle-yiden >}} who loved Yiddish theater and who were always ready to help a wandering Yiddish actor out.

In general, those {{< var voyle-yiden >}} played an important role in the lives of the Yiddish actors, who for many years traveled the provinces playing Yiddish theater in all the cities and towns of America. If it weren't for them, the situation of the traveling Yiddish actors of would have been much worse, not knowing who, in these cities far from home, was well-connected or how to earn a piece of bread from some performances.

This is indeed why I have to mention those {{< var voyle-yiden >}}. They earned it. And by the way, I want to say that there were also those among them whose love for the Yiddish theater, little by little, drove them to become "stage managers" as a kind of side income for them. You could find a lot such stage managers in many cities in those days. In Pittsburgh too we had someone who was something of a stage manager. He took care of us and took on the job of acquiring a theater and providing the necessary wardrobe for the performances. This was a side gig for him, and he already had a bit of experience in this.

In Pittsburgh, we played {{< var lateiner-full >}}'s piece {{< var lostsoul >}}, and {{< var schoen >}} gave me the role of {{< var shabtai-golem >}}. I really enjoyed and felt elevated by this because this role had good singing and speaking parts, and you could stand out in front of the audience.

I was a really big hit with the song {{< var wiseson >}}. The audience simply did not want to let me off the stage, and I had to sing the couplet over and over again. And that was of course not just because I sang the song so well, but also because the song was very popular in those days. Everyone knew the song, and it was sung everywhere.

As an experienced actor, I already knew that the more popular a song is, the more people want to hear it. Certain that even before I started the audience was already with me, I immediately became lively and cheerful, and I went out on the stage with a bang: 

_Lyrics._^[Most of the lyrics of this song are too complex for me to reliably translate.]


And, with a snap of my finger and a wink of my eye:

> The wise son!
>
> The wise son!
>
> The wise son - 
>
> from the four questions.


You could call this a kind of "entrance;" with this I introduced myself to the audience in the role {{< var shabtai-golem >}}. And soon after, as was the usual custom, in singing the song, delved into "lebensphilosophie"^[["philosophy of life" philosophical movement](https://en.wikipedia.org/wiki/Lebensphilosophie) based on the idea that life, not spirit, is the true foundation of the universe], and I was pleased that the audience already knew what was coming next and that everyone already {{< var kvelled >}} even before it came, and I sang with even more enthusiasm:

_Lyrics._

As usual, this was a big hit with the women in the audience. They laughed loudly and applauded with great enjoyment. And I, contented, sang on:

_Lyrics._

In general the song {{< var wiseson >}} really hit the spot for women since it made fun of men. The song began and ended with the line "The wise son of the four questions," and in the end came the part that everyone really looked forward to, ready to burst out laughing.

_Lyrics._

It is hard to convey in words how this all happened in the Pittsburgh theater. Their laughter and their applause became stronger and stronger. I had to sing the last couplet over and over again. In the role of {{< var shabtai-golem >}}, I was instantly beloved from just the first performance. And as I have already said in a previous chapter, in my writing I consider it necessary to share certain songs from the past - songs that brought so much joy into the hearts of thousands and thousands of Jews.

In that piece {{< var lostsoul >}}, there was also a song called {{< var purim-nes >}}. A young girl who played the role of {{< var bobele >}} sang that song. This was a serious song, and people took it very seriously. Like most of the serious songs from the Yiddish theater of that time, it was based on the history of the Jews while also being connected to events of the end times.

This song is also worth sharing. It went like this:

> We praise you, God, today with holy songs,
>
> In honor of {{< var purim >}} we dance and rejoice.
>
> Your Jews give thanks to you, our God,
>
> For the great miracle that befell us. 
>
> Your holy people, {{< var veyismir >}}^["woe is me"], 
>
> Have fallen before the enemy's sword,
>
> Haman, {{< var yimakh-shemo >}}^["may his name be erased"; a [classic Jewish curse](https://en.wikipedia.org/wiki/Yimakh_shemo)], nearly completed wiped the Jews off the face of the earth.
>
> The {{< var tzaddik >}} Mordechai, of blessed memory^[This might be "thanks be to him"? זכר לטוב], rescued us from this great calamity.
>
> Haman became the {{< var kapara >}}^[From [kapparot](https://en.wikipedia.org/wiki/Kapparot), implies Haman's death was a redemption for the Jews] for us, 
>
> To all enemies, oh God, bring such an end.

This song always began with _Haman Haroshe_^["Haman the Evil"]. {{< var lateiner-full >}}'s piece {{< var lostsoul >}} also started with this song. The young girl who played the role of {{< var bobele >}} in Pittsburgh sang with song with heart and feeling. The audience swallowed every word and gladly listened on:

> In every generation today, just like before,
>
> We have enemies, just like dogs;
>
> In these troubles, our God, is your people Israel,
>
> Help us, our Father, from the Hamans today as well!
>
> Millions of Jews cry out, oi, in every country, where they are mercilessly oppressed.
>
> Oi, the drunken Cossack, {{< var yimakh-shemo >}} - 
>
> Send him, our God, to the place where you sent his father...
>
> Hear my prayer, oi, {{< var rebbeinu-shel-olam >}}^[lord the world], 
>
> Show us the miracle of Purim again today!
>
> Oi, send a bomb to the the Cossack fool,
>
> And also to all their kin...


That is how the song {{< var purim-nes >}} went in {{< var lateiner >}}'s piece {{< var lostsoul >}}. And from how the song cursed the Russian tsar, you could tell it was written during the period when Alexander the Third sat on the throne. You could tell from the meaning of the words that God should send him "where he sent his father," Alexander the Second, who the [revolutionaries killed in St. Petersburg with a bomb in the middle of the street](https://en.wikipedia.org/wiki/Assassination_of_Alexander_II_of_Russia)... 

It was very common that, in the free land of America, Jews would curse the Russian tsar on stage quite openly. Nobody was afraid to do so. And I still remember how {{< var abba-full >}} himself took such great pleasure in hearing {{< var bobele >}} sing the song {{< var purim-nes >}}. This song was very pleasing to him, and he himself also excelled in the dramatic role he played in the piece. And he was very happy that the box office income in Pittsburgh was really good - thanks to this, he could do more for his children, who he loved so much...

It is really difficult to find such a faithful father as {{< var abba-full >}} was.
