# November 28th, 1946

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1946/11/28/01/)_ {.unnumbered}

> My wandering around the provinces. -- {{< var gordin-full >}} comes to St. Louis to stage the play [{{< var mirele-efros >}}](https://en.wikipedia.org/wiki/Mirele_Efros)^[Information about the [1939 film](https://jewishfilm.org/Catalogue/films/mireleefros.htm).] and I perform in the play. --  Yiddish actors' attitude towards {{< var gordin-full >}}.

During the half-a-year that we played in Cincinnati and things went well for us, I corresponded from time to time with my old friend {{< var karp-full >}}, and I made him an offer to come to Cincinnati and play together with us.

I remembered that it would be good when he came to us, and in the letters that I wrote to him, I always mentioned that, as for his children who he always brought with him because he loved them very much, he doesn't need to worry at all, because it is more than certain that here with us in Cincinnati, he will definitely find a nice respectable family who take good care of them and they will feel as though it was their home, and it won't cost him a lot.

But {{< var karp >}} was always busy with his travels all around other cities; It seemed he had no desire to come to us, and when, finally, he did come, it was already getting towards the end [of our time in Cincinnati] and things were not going so well for us. {{< var karp >}} immediately took a dislike to Cincinnati and on all the good Jews around us, and he insisted that we go with him to Louisville, Kentucky.

-- Why have you become so sullen about Cincinnati? - he scowled. - _Cincinneti, Cincinn-shmeti_... Now, Louisville, Kentucky - _that_ is a city!...

And so we left and went to Louisville, Kentucky, and there we put on several performances, and then something I didn't expect at all happened...

Just then when were playing in Louisville, Kentucky, {{< var tanzman >}} arrived there with his troupe. {{< var Nu >}}, as you might expect, competition between us started right away, but that didn't stop the actors and actresses from both troupes from meeting up and spending time with each other. And it ended with someone from our troupe having an affair with one of {{< var tanzman >}}'s sisters, and she immediately admitted into our troupe. We all became close pals with each other, and in the end they all went off together to play in another city and I was left behind, just as if I was a spare part...

{{< var schoen >}} even tried to stand up for me. But interceding for my wife and I did not help, because the actor's love affair with {{< var tanzman >}}'s sister - who, by the way, was really quite beautiful - created a situation where the troupe didn't need me and my wife any longer, and on top of that, there were the usual series of^[again, he uses סדרה here, which implies a regular/expected order] intrigues and reminders of old feuds, so I could no longer be in the troupe.

All these things are very characteristic of the chaotic situation that prevailed in our Yiddish theater world in those times. Nobody had contracts, nobody owed each other anything, you were always subject to the whims of this and that, and it was quite a common thing that, over some affair that lasted no longer than the Fast of Esther at {{< var purim >}}^[This is an idiom (note there is indeed a [Fast of Esther](https://en.wikipedia.org/wiki/Fast_of_Esther)) meaning that something does not take a long time or ends quickly/abruptly. So, {{< var sam >}} means that the it didn't last longer than something that already is over quickly - it was _extremely short-lived_], a troupe would go through complete upheaval and completely abandon some actors, who would get left behind...

I really resented that I was treated that way. I felt sorry for myself that I had to part with such good friends as {{< var abba-full >}}, {{< var frank-full >}}, and {{< var jakele-full >}}. But I had no other choice, and my wife and I back to our family in Philadelphia, the same city where I settled after I arrived in America with a lot of high hopes. We lived off the money we had saved from the good times we had had in Cincinnati, we started preparing and I hoped that I would not go around empty for a long time.

At that time I was already a father of two children. We had a son and a daughter^[Their daughter Lily was born April 1898 in Cleveland, so we are now in either in late 1898 or 1899]. And when week after week went by and I still had nothing to show for myself, I became very restless. I must have been restless, because the little sum of money I had saved up in Cincinnati was growing smaller and smaller. It had already "run dry," as we used to say. I left for New York, and with full confidence that by now people would have heard a lot about me there and they certainly knew about the great success I had had in Cincinnati, I went to {{< var thomash >}}, and also to {{< var adler >}}, and asked them to hire me.

Both of them - {{< var thomash >}} and {{< var adler >}} - had indeed heard a lot about me. They knew about the success I had in Cincinnati, because I made sure that they would know about it. But they were not greatly impressed by this; they received me well and complimented me, but they did not hire me.

Coming back from New York with nothing didn't suit me at all. I just hung around like this for a while until I heard that my old friend {{< var frank-full >}}, {{< var der-roiter >}}^["the red one"], as we called him, had also lost his job; He was pushed out of the troupe over the series of intrigues related to the affair which I mentioned earlier...

When I heard that {{< var frank >}} was pushed out of the troupe I was very glad, because he, {{< var der-roiter >}}, always stood by me throughout times of hardship, and whenever I was left behind, we always "teamed up," as we say in Ukraine^[Ukrainian yiddish dialect], and we set off to find our luck in the provinces...

He was always ready to travel, and with him you could act in plays, in sketches, or just fill an evening singing songs of all kinds.

{{< var frank >}} could do anything. He was indeed a good comedian, and there is no doubt in my mind that if he weren't so negligent and if he had only had more ambition and the desire to work on himself, he would have occupied a more prominent place on our Yiddish stage.


Together with {{< var frank >}}, I then left for Cleveland, our wives also joined us, and soon we had a troupe and we played {{< var lateiner-full >}}'s historical operetta called {{< var kiddush-hashem >}} - a play named with an "or," as was the style in those days...

Without an "or," a writer at that time couldn't make any headlines. And if there was not an "or" in the name of a play, because the writer thought that it was not necessary, the director of the theater provided one himself...

At that time, we brought the actor {{< var s-weintraub >}} and his wife, the talented actress {{< var r-weintraub >}}, down to Cleveland, and we really hit the jackpot with both of them in our small troupe; {{< var weintraub >}} was not only of those actors who was honest in his acting, but also of those people who is honest in their relationships. In addition, he was intelligent, he understood people, knew how to get along with them, and on top of all his virtues, he always came up with a way to get out of a hard time and improve the situation when we needed to work out a new plan.

Together with the {{< var weintraub >}}s, we played in Cleveland for a little while. After that, we traveled around other cities. Like gypsies, we {{< var schlepped >}} around to the ends of the land. And when, as it usually happened, later people started to quarrel over some foolishness, I left the troupe and then {{< var tanzman >}} let me know that he no longer had a problem with me and that he was ready to let me join and he invited me to come to him in St. Louis, where he was stationed with a troupe...

Dropping out of a troupe, or joining a troupe in such a manner, was no nothing new. Just like they {{< var schlepped >}} around like gypsies, they also fought like gypsies and then reconciled. And when they reconciled, you still couldn't know how long they would last together, because just like that someone could easily fall out of a troupe - the whole troupe could easily fall apart and there wouldn't be anyone left...

​​In St. Louis, {{< var tanzman >}} handled himself with skill, and when business was not so good, he would bring down a star from New York. I  remember how once he brought down Madame {{< var keni-full >}} not alone, but together with the famous dramatist {{< var gordin-full >}}.

Madame {{< var keni >}} performed in two plays in St. Louis - [Grillparzer](https://en.wikipedia.org/wiki/Franz_Grillparzer)'s [{{< var medea >}}](https://www.gutenberg.org/cache/epub/7945/pg7945-images.html), which {{< var gordin >}} translated into Yiddish, and in {{< var mirele-efros >}}, which he wrote specifically for her. In the play {{< var mirele-efros >}}, I was given the role of younger son Daniel, who the actor [{{< var sam >}}uel Tobias (Tabatshnikov)](https://www.museumoffamilyhistory.com/yt/lex/T/tobias-samuel.htm)^[Yes, {{< var sam >}} writes both!] played in New York when the play was staged in New York for the first time. Tobias's name was famous in the Yiddish theater world; he was considered a good actor and a good singer, so I was therefore terrified when I was assigned to play his role, and even moreso in a performance where {{< var gordin-full >}} himself will be there. That's why I really girded myself when I played the role; I really wanted my acting to stand out to the famous dramatist, who made such an impression with his beautiful beard and his poise that all the actors simply trembled before and had the greatest respect for him. And I was really very pleased when, after the performance, I heard him say to Madame {{< var keni >}} in Russian, that "Kestin, who played the young boy Daniel, was very good in the role"...

I feel such high esteem and joy and when I heard this from his own mouth, and I boasted about it to everyone.

And here I want to pass along something that is really worth sharing, because there is a good moral to this story:


This was on a Saturday night, after a performance of {{< var mirele-efros >}}. The audience in the theater then gave {{< var gordin >}} an ovation, and he went up on the stage and bowed, and the theater simply lit up with applause. And all of us, the actors on the stage, felt small amid his greatness...

And after the applause died down and the curtain was lowered after the last act, Gordin said that he was interested in going to a Turkish bath...

He asked who wanted to go with him in the Turkish bath, and needless to say, the actors immediately expressed their interest in it. That was really something - to have the honor of going with {{< var gordin-full >}} himself, with the great Yiddish dramatist, to a Turkish bath!...

I was also among the interested. And when we went with him to the Turkish bath, we behaved in a very dignified and serious way, and we approached him like yeshiva students to their teacher. None of us dared to say a word that might be unbecoming to say in front of such a great and famous man...

Even after we had already warmed up in the sauna and sat down in one of the rooms, wrapped in towels, we all behaved very seriously. Even just wearing towels, we still behaved seriously.

And suddenly, to everyone's surprise, he, {{< var gordin-full >}} himself, started telling jokes...

He told us one joke after another until he moved on to completely cynical jokes...

And when we heard that, we simply couldn't believe our ears and we glanced around at each other...

-- Wh-a-a-t? Him too...?

If we hadn't heard it ourselves, we would have found it difficult to believe such a thing...

And I have to say that after that, we looked at him with completely different eyes and we started to lose the respect we had had for him before...
