# A blast from the past

::: {style="text-align: right;"}
Published in the {{< var forverts >}} on [ November 30th, 1946](https://www.nli.org.il/en/newspapers/frw/1946/11/30/01/)
:::


> In a troupe with the famous opera singer {{< var medvedev >}}. -- Why {{< var thomash >}} came all the way to Chicago to invite me to play in the People's Theater^[Formerly located at 199-201 Bowery, between Rivington and Spring Sts].


Among the cities where I performed Yiddish theater in those times when I {{< var schlepped >}} all over America with wandering troupes, Chicago must also be mentioned. I can't leave the city out - not only because it was hard for me until I arrived there, but also because some things happened there that are etched in my memory, and it's worth mentioning them because they are connected with the history of Yiddish theater in America.

In playing in Chicago, I was no longer surprised by where life would lead me or where I would spent my days or nights. I came to Chicago to a real^[{{< var sam >}} uses the word "fixed"/"designated"; implies this theater is really a specific institution, not just a place the wandering actors found and rented out for a time] theater where a permanent troupe played, and the manager of the theater was [{{< var glickman >}}](https://www.museumoffamilyhistory.com/yt/lex/G/glickman-elias.htmvar)^[Read a [blog post about {{< var glickman >}}](http://undereverytombstone.blogspot.com/2013/10/he-brought-yiddish-theatre-to-chicago.html). According to his obituary, which is shown in the blog post, this theater was called "Metropolitan Hall" and was at the corner of Jefferson and O'Brien streets.]. {{< var glickman-full >}}, a Jew who knew how to manage a theater, had a dream to create such a venue for the Yiddish stage in Chicago that people wouldn't have to be ashamed of not being in New York.

{{< var glickman >}} himself once also dreamed of becoming an actor. In his younger years when he still lived in the city of [{{< var zhitomir >}}](https://en.wikipedia.org/wiki/Zhytomyr), he had participated in Russian, Ukrainian, and also Yiddish performances. When he came to America, he played on the stage too, and he loved it so much that even when he was given the lowly role of an extra, he was satisfied. However, he soon realized that he was more suited to the business side of the theater than to acting on the stage. As he was not lacking in such skills and had made money in business, he became a theater manager in Chicago. He conducted business such that it was understood that when he hired an actor, they would no longer have to wrack their brain over where to find an income because he took care of them.

At first, {{< var glickman >}} hired my wife. Apparently, he didn't have any desire to engage me then, or he didn't need me. But a few weeks later he sent for me, and when I arrived, he advertised me very well. In a short time I became one of the pillars in the troupe. I appeared in prominent roles, and he was very satisfied with me.

In general, I was able to get along with people wherever I went; I was never one of those people who started fights. I could, and I still can, swallow a lot of things that weren't worth making a fuss over. I only got angry when people insulted me for no reason...

At {{< var glickman >}}'s theater in Chicago, I also got along well with the troupe, and I was satisfied that I didn't have to {{< var schlep >}} around like before. And no matter how much my wife and I earned, it was enough for us, and we were happy with the fact that we had such precious children.

With this, I don't intend to present myself in such a light that you'd think I was a homebody or that I was a paragon of serious or dignified behavior. No, I wouldn’t say that. I confess, when I was making a good living, I liked to go out with friends and acquaintances and have a good time. I usually did not refuse a good glass of wine and a good bit of liquor, and I knew how to live it up^[also translated as "run wild"] so that no one I went out with would be sad...

That's the kind of person I was. But I still knew "where one and how finished"^[This is an idiom I cannot translate, but I assume it means "when to behave this way and when not to" or similar]. And I have always loved my family, and my wife and children have always been very dear to me. I mention this just because it just came to mind while writing. And now I will continue to tell you about the times when I played at {{< var glickman >}}'s in Chicago.

As an experienced theater director, {{< var glickman >}} maintained that it was necessary to always have something new to attract the audience as much as possible. Because of this, from time to time, he would bring an actor with a big name to Chicago from New York. And when he once heard that there was a big fuss in New York over the opera singer {{< var max >}}, who came from Russia to America and was performing on the Yiddish stage, he didn't think twice about it, and he brought him to Chicago.

{{< var medvedev >}} was never much of an actor. He was merely a good singer, and in his younger years he excelled with his singing. But when he was brought to America, his voice wasn't the same as it used to be, and when people heard him sing, they were disappointed...

But it was still a bit of a sensation. People talked a lot about an opera singer stepping out onto the Yiddish stage to perform alongside all the other Jewish actors in the play. That alone was a sensation, because people had heard a lot about {{< var medvedev >}} before. And indeed that is why {{< var glickman >}} brought him down to Chicago.

Because of him {{< var medvedev >}}, in Chicago we put on a piece that bore the same the name of the famous opera {{< var zhydovka >}}^[_The Jewess_; this is the Russian translation of the French opera [_La Juive_](https://en.wikipedia.org/wiki/La_Juive)], and in it {{< var medvedev >}} sang the famous aria in Russian {{< var rachel >}}^[In French, "Rachel, quand du Seigneur"; In English, "Rachel, when the Lord." Listen to the [song in Russian on Spotify](https://open.spotify.com/track/50FwruRJqW6E3Ps1t7w3sj?si=1776f45cef5c4ede).].

He sang it beautifully. His voice sounded strong. But the performances put on with him did not have any great success, and they did not warm up the audience. The whole story of playing Yiddish theater with an opera singer who spoke {{< var chetzi-goyishe >}}^["half-goyishe"] Yiddish and sings arias in Russian did not appeal to audiences, and they were not enthusiastic about it...

It didn't stick.

{{< var medvedev >}} himself did not feel at home on the Yiddish stage. He also felt like a stranger among the Yiddish actors. That's how it seemed. And I remember how at the first performance, when {{< var medvedev >}} was sitting by himself in the dressing room between scenes, pensive and apprehensive, I went to him and started speaking in my broken and stilted Russian, of which a little still remained in my memory. And when I told him that my name back home was not {{< var kestin >}}, but {{< var konstan >}} and that I once went to a {{< var heder >}} in the {{< var shtetl >}} {{< var rybinka >}}, he was startled:

-- In {{< var rybinka >}}?!...
-- Yes, in {{< var rybinka >}}!

And then I reminded him of the time when he was whipped in the {{< var beit-midrash >}}^[Recall the events of [Chapter 4](./04_1946-09-25.qmd)]. When he heard this, he loudly burst into laughter, and when he was done with his good laugh, a deep sadness suddenly spread across his face, and he said:

-- Yes, those were the days... I was still young then... and everything was ahead of me... not like now... now everything is behind me... in the past...

This is how the fallen Russian opera singer {{< var medvedev >}} spoke. And when he said this, I saw him before me as he once was - Meïr the synagogue choirboy, the son of the {{< var rokitna >}} Rabbi and the brother of the {{< var rybinka >}} butcher {{< var Yehiel >}}...

A piece of the Jewish past from the two small Ukrainian {{< var shtetl >}}_s_, {{< var rokitna >}} and {{< var rybinka >}}. And then suddenly {{< var rybinka >}} was transported here right before my eyes in the form of some strange metamorphosis on the Yiddish stage, in the city of wind and smoke - in Chicago...

Just at that time - and this, I believe, must have been in the year 1900 - the [Actors' Union](https://en.wikipedia.org/wiki/Hebrew_Actors'_Union) in New York called a strike at the People's Theater^[According to [YIVO records](https://archives.cjh.org/repositories/7/resources/554), this strike took place in December 1899]. When we, the Yiddish actors in Chicago, heard this, there was an immediate uproar. And it was no wonder - many Yiddish actors in the provinces who {{< var schlepped >}} around like gypsies from city to city were angry because they were not part of the union, and therefore they could not show any great solidarity with the strikers. They thought that they should have the opportunity to strike too...

Once, when I was sitting with {{< var medvedev >}} in his dressing room between shows, talking with him about the {{< var shtetl >}}_s_ we both knew well - about Arkitne, about {{< var rybinka >}}, about {{< var vasil >}}, about [{{< var talne >}}](https://en.wikipedia.org/wiki/Talne), {{< var bt >}}, and about other {{< var shtetl >}}_s_ - two Jews came in and told me that {{< var thomash >}} had sent them to me. {{< var boris >}}, of New York; They came to Chicago specifically to see me...

At that moment, the actor's strike in the New York People's Theater was completely out of my mind. I looked at the two Jews, astonished, and I asked them:

-- For what reason, tell me, I implore you, did Mr. {{< var thomash >}} send you here to me from New York?

-- He wants you to come and play with him...

Only then did I suddenly realize what their intentions were. I instantly remembered the strike, and it became clear to me what they wanted - they simply wanted me to come to New York to be a scab. And I answered them very sternly:

-- Tell {{< var thomash >}} that I said if he wants to hire me, he should choose a more appropriate time. Also tell him this - I am not a scab!

-- We'll give you \$500 right now. - one of them said. - \$500 right here on the spot...

They thought that I would surely take it. But I answered them coldly:

-- Even if you gave me ten times as much, I still wouldn't go...

While the conversation was going on between me and the two Jews, whose names I don't want to mention here, {{< var medvedev >}} sat with a sullen expression, measuring the two Jews up from head to toe. And suddenly he put his hand on my knee and started speaking in Russian:

-- Take the \$500 from them... take it and send the money to the strikers!...

He was sure that the two Jews did not understand Russian. But in fact they did understand Russian, and they got angry at him.

-- What a fool... He wants us to give the money away for nothing...

Needless to say, I didn't go to New York to play at that time. But in the troupe there were some actors who did go to New York to play, and they tried to justify it by saying that they don't want to join the union...

There is an excuse for everything. Even for being a scab...

But I will not give the names of those actors. It's better not to mention this...

