# December 5th, 1946

_This article is not available from the National Library of Israel. The article was obtained from the New York Public Library's microfiche archives._

> [{{< var simonoff >}}](https://www.museumoffamilyhistory.com/yt/lex/S/simonoff-moshe.htm)'s constant "no" in the {{< var hau >}}. - [{{< var ivan-abramson >}}](https://www.museumoffamilyhistory.com/yt/lex/A/abramson-ivan.htm) and the comedian [{{< var berl-b >}}](https://www.museumoffamilyhistory.com/yt/lex/B/bernstein-berl.htm). - Why people called him {{< var b-hope >}} ^["Hope" as used here does not mean hope as in English; it means either "hup/hop!" as in, "_hup_, let's go!", or "hop" as in hopping/skipping around].


The strike that the Hebrew Actor's Union waged in New York's People's Theater led to a complete revolution in our little theater world The union won the strike, and from then on the actors stopped playing for "stamps" and started receiving weekly salaries.

When we heard in Chicago that the strikers at the People's Theater in New York had won, we were very happy about it. And after we finished the season in Chicago, I left for New York, and I was sure that I would certainly be accepted into the union there very soon, because they already knew how well I reacted when they offered me money to come and play at the People's Theater during the strike.

This alone - that I behaved like a good union man even before I was accepted into the union - was, in my opinion, enough for them to see as one of them, as someone who deserves to be a union member - not to mention the fact that I already had a name as a good comedian and people had already heard a lot about me in the Yiddish/Jewish circles in New York.

At that time, I wanted very much to be admitted to the union and to be able to settle in New York with my family, because I was tired, so very tired, of {{< var schlepping >}} around the cities and towns where you never knew what would happen to you or where you would end up next. I was sick of wandering around and I wanted to have a permanent home.

But they didn't want to admit me to the actors' union. They locked their doors to me, and I remember how at that time I heard that the actor {{< var simonoff >}} waged a campaign - for every candidate who came to try out for the Actor's Union, the vote should be - "No."

A lot of jokes were told in theater circles at the time about {{< var simonoff >}}'s constant "No" vote for new candidates of the Actor's Union. Jokes that really made you laiugh out loud. But I did not find it funny, and I left New York with a deep sorrow in my heart and settled again in Philadelphia, as I always used to do when I was eagerly on the lookout for my next steps and racking my brain about what will happen to me later.

From the experiences I had already had, I knew that I would not fail; I'd find something, somewhere to earn my piece of bread. And so it was.

Before the summer ended^[the summer of 1900], a Jew with a big name in the Yiddish theater world came to Philadelphia, and soon it became known that he was putting together a troupe, a Yiddish troupe, who would play the whole season in Columbia Theatre^[Located at 3rd and Green Streets, in the Northern Liberties neighborhood].

That Jew was named {{< var ivan-abramson >}}. He was the husband of the Yiddish actress [Lisa Einhorn](https://www.museumoffamilyhistory.com/yt/lex/E/einhorn-lisa.htm), who played the first {{< var shulamith-role >}} on the Yiddish stage in 1880. {{< var ivan-abramson >}} came from Russia, and it was said that he came to America when he was still a young man of 16 or 17 years old, and he was one of {{< var gordin >}}'s first followers. He loved Yiddish theater, and he had literary pretensions and had once published a humorous weekly in New York called {{< var pok >}}^[This was a satirical paper published in New York from 1894-1986. According to [this book chapter](https://doi.org/10.3828/liverpool/9781874774730.003.0013), "{{< var pok >}} (its editors rendered it as the _Hebrew Puck_) was a vaguely socialistic, humorous monthly, and eventually weekly, which contained cartoon images mainly stolen from the popular American and German-language satirical press and re-captioned in Yiddish."].

In general, Ivan was one of those people who threw money around. And every time, when he took on something new, he talked about it with enthusiasm that talked it up as something grand, very grand. When he began to assemble the troupe in Philadelphia, he also talked about it like this - that it could really mean that soon Philadelphia could surpass New York. When he engaged me to play with him at the Columbia Theater, I was very pleased and I did not complain about the wages; It turned out that my wife and I, together, would both receive twenty-five dollars a week.

The troupe consisted of actors who were already known. I remember that these actors played in the troupe: [Joe Kessler](https://www.museumoffamilyhistory.com/yt/lex/K/kessler-joseph.htm), [Elias {{< var rothstein >}}](https://www.museumoffamilyhistory.com/yt/lex/R/rothstein-elias.htm), Samuel Shneyer, [Madame Rae Shneyer](https://www.museumoffamilyhistory.com/yt/lex/S/shneyer-rae.htm) and many others. But the leading actor was Berl Bernstein, who was known as a very good comedian, and audiences loved him very much.

It was not easy to get along with the comedian {{< var bern >}} in a troupe, because he was very jealous of others, and if he ever saw that another actor was a big hit with audiences in a role,  saw how an actor took him in front of the audience in a role, he couldn't rest and he ate himself alive over it.

That's the kind of person {{< var bern >}} was, and he couldn't be different even if he wanted to. It could not have been pleasant for him, because it took a real toll on his health, but he could not help it because that was his nature. And in the theater circles, people called him {{< var b-hope >}}. 

He was given this nickname because, in every role he played, he would frolic and skip around, and it was impossible to get him to stop^[In other words, he dominated and took over the whole stage]. In general, he was one of those actors who usually played "solo" and was so engrossed in his own role, and it didn't matter to him that he often took it so far, that it didn't even make sense with with plot of the piece...


I had to put up with a lot from {{< var bern >}} in {{< var abramson >}}'s Philadelphia troupe, because as soon as I was selected for a role, he couldn't stand it and he treated me with scorn....

The first time I swallowed everything, but after that it started to irritate me, and I looked for ways to show him that I would not be intimidated.

One time, when we put on {{< var lateiner >}}'s piece {{< var blimele >}}, I was asked to play the role of {{< var zeligel >}}, a role in which {{< var mogu >}} himself really excelled. And as always, when I only had to play a role in which {{< var mogu >}} himself excelled, I worked really hard to prepare, and this time was no exception. I studied the role of {{< var zeligel >}}, and above all I studied the couplet which {{< var zeligel >}} sand as a duet with {{< var zirele >}}:

> _Lyrics._

I was very familiar with all of the little idiosyncracies and gestures, which were all full of charm, that {{< var mogu >}} did during the song, because I had seen him many times in the role of {{< var zeligel >}}. I tried to imitate him as much as I could, and I was very eager to see how it would go for me on stage.

I was really looking forward to the moment when I would appear on stage in the role of {{< var zeligel >}} the poet in {{< var lateiner >}}'s play {{< var blimele >}}, which was so popular with the audiences. But suddenly when the play was announced, my name was left out.

This really angered me, and I complained to the director, to {{< var ivan-abramson >}}:

-- What is this, not announcing me in the role of {{< var zeligel >}}? What, are you ashamed of me?

Just then, when I went to {{< var abramson >}}, {{< var berl-b >}} was also sitting there and he said something to me like - I shouldn't be upset about it because I should be pleased that I got to play on the same stage with such an actor as {{< var berl-b >}}...

His behavior toward me offended me, and I spoke up for myself:

-- What was that, {{< var b-hope >}}? I will not stand for this!

And I told him angrily that he would also not be able to perform in {{< var blimele >}} either, because since I was not announced, I won't play the role of {{< var zeligel >}} at all, and we will not be able to put on the play at all.

When {{< var bern >}} heard this, he immediately softened and started to persuade me that this omission was nothing more than an oversight. {{< var abramson >}} also persuaded me that no one was trying to offend me. And I forgave them and ended up I playing the role, and I was a big hit on the stage.

But my heart still told me that this was not an oversight, but that they were actually trying to suppress me. And afterwards I found out that I was indeed correct, as I will explain later. And I can assure you that it will be interesting, because it is related to the theater politics of those times.

