# December 7th, 1946

_This article is not available from the National Library of Israel. The article was obtained from the New York Public Library's microfiche archives._

> Luck finds you when you least expect it. -- Characteristics of the sullen man [{{< var yosele >}} {{< var edelstein >}}](https://www.museumoffamilyhistory.com/yt/lex/E/edelstein-joseph.htm).


My suspicion that it was no mere coincidence that my name was not announced for performance where I played {{< var mogu >}}'s role was not unfounded.

You could tell from how later, when the piece [{{< var kol-nidre >}}](https://digitalcollections.nypl.org/items/510d47da-db4b-a3d9-e040-e00a18064a99)^[[Article about the historical context](https://ingeveb.org/articles/kol-nidre-and-the-making-of-the-jewish-theatre-audience) of this play in the history of Yiddish Theater] was staged, my name was again not announced, even though I played a major role. It was clear to me that this was all because {{< var berl-b >}} was a _jealousnik_, and he simply did not want my name to stand out.

I couldn't blame him that he wasn't able to treat me fairly, because as I've already told you, it's possible that he did not enjoy that he got so jealous of the other comedians on the Yiddish stage. Perhaps he just couldn't help himself because that was his nature, and he just couldn't change it...

And he was not the only one who had such a nature; Such actors have always been on the Yiddish stage, even now still. You can also find many such actors on the non-Yiddish stage, too. Some show it more, and others show it less.

Many times, I thought that the comedian {{< var berl-b >}} suffered from this illness, and I was ready to forgive him and not hold it against him. But I myself am also an actor, and an actor, you must know, cannot remain silent when his name is not announced...

It hurts so much that you simply can't be silent...

One time, when we were getting ready to put on {{< var goldfaden >}}'s historical operetta {{< var shulamith >}} in {{< var abramson >}}'s theater, they gave me the comic role of the {{< var tsing >}}, who follows {{< var avisholem >}} around the whole time. And I really liked to play {{< var tsing >}} and I had already worked out how to sing his disturbing little song:

> _Lyrics._

It was explicitly promised that this time my name would not be left out, and they will specifically announce that I, the comedian {{< var sam-full >}}, will play the role of {{< var tsing >}} in {{< var shulamith >}}. But they didn't keep their word; They announced that the role of {{< var tsing >}} would be played by {{< var berl-b >}}, even though I was playing the role...

That's what they decided, and when I complained, they tried to weasel out of what they did with all kinds of excuses, but this time it didn't work.

When this happened, I felt so restricted at {{< var ivan-abramson >}}'s theater that I could no longer stay there, and I firmly decided that I would not play the role of {{< var tsing >}} in the performance of {{< var shulamith >}}.

-- Let {{< var bern >}} play the role - I said angrily. - He has been announced in the role, he should play it. Not me!...

At that time, {{< var mike >}}, one of {{< var boris >}}'s younger brothers, owned and was the director of the [Arch Street Theater](https://en.wikipedia.org/wiki/Arch_Street_Theatre) in Philadelphia. The famous actor [{{< var feinman-full >}}](https://www.museumoffamilyhistory.com/yt/lex/F/feinman-sigmund.htm) played there with a troupe, and he performed {{< var gordin-full >}}'s piece {{< var devil >}} as well as others of the best repertoire pieces. In those times, in general - not only in Philadelphia but also in New York - they would put on the old repertoire; At the beginning of a season, people did not look for a new play, as is the case today. It started with repertoire and ended with repertoire. And no play that was popular with the audience and where the actors really had something to play was ever taken off the stage.

That's how people used to behave. And there was always a crowd that gladly came to see the same play when another well-known actor played the main role. They wanted to see the difference between this actor and that actor, and afterwards they had a whole discussion and debate about it...

I went to {{< var feinman >}} and he talked it over with {{< var mike >}}, and immediately I was accepted into the troupe. They announced on stage that from now on, the comedian {{< var sam-full >}} will no longer play in the Columbia Theatre, only here in Arch Street Theater. And they gave me many opportunities to appear in good pieces from the old repertoire, and I felt good there.

There was fierce competition between the two Yiddish theaters in Philadelphia, and each always wanted to prevail over the other. That's why everything was always so chaotic. Each was always trying to head the other one off. They simply tried to catch the other one with their hands tied behind their back, and as a result business in both theaters started to go very badly, and all around everyone was very unhappy.

In the chaos, we, the actors of the troupe, had to work very hard because no play lasted long enough to warm up the boards on the stage; Today we put on one play, and tomorrow we put on another. We were always busy with rehearsals. People were always coming up with new ideas, always looking for ways to make the best of a bad situation.

One time when I was wandering around backstage at a performance and waiting for my cue in some role I was playing, I heard a bell boy from a hotel ask one of the actors, "Who here is Mr. {{< var kestin >}}?"

I hurried to him:

-- I am Mr. {{< var kestin >}}!

The bell boy handed me a little note and told me that I must give an answer right away, because they were waiting. And just then, as though out of spite, they called me up onto the stage for my cue, and I wasn't able to read the letter yet...

I was wracked with impatience, and I really wanted to know who the note was from and what it said. But I had to be patient. As soon as I finished my scene and went backstage again, I read the letter and it immediately brought joy to my heart...

This was a letter from {{< var boris >}} and {{< var edelstein-full >}}, the owners of the People's Theater in New York... They both came to Philadelphia and are now waiting for me in a hotel... They wanted to hire me to play In New York, and I should let them know, through the bell boy, whether I would come to talk it over with them when the show was over...

I really did not expect such a thing. Who could have imagined that {{< var boris >}} himself, together with {{< var edelstein >}}, would come from New York to Philadelphia specifically to hire me?...

It goes without saying that I immediately sent the bell boy back to them with an answer, that I will come to see them. And when I went to their hotel after the show, {{< var boris >}} didn't started talking to me directly about it, but danced around it a bit. But {{< var edelstein >}} soon interrupted got straight to the point:

-- Listen to what I will tell you - right away, as was his way, he started talking to me informally^[Yiddish has two pronouns for the singular "you" - an informal and formal version. Here, {{< var sam >}} means that {{< var edelstein >}} immediately used the _informal_ "you" pronoun with {{< var sam >}}, not the formal one.] - We want to hire you to play in "People's Music Hall." How much do you want?

He gave no further introduction.

Hearing that they didn't want to hire me to play in the People's Theater, where they put on plays and where the famous {{< var jacob-adler >}} was one of the three managers, but instead in "People's Music Hall," where they played vaudeville, my heart got a little colder. I was not as excited as I was before, and I replied that I would agree to play in the music hall only on one condition.

-- And what is the condition? {{< var yosele >}} {{< var edelstein >}} asked, undeterred. - By all means, we're listening...

-- The condition is, - I answered him, - that I will play in the music hall, if you agree that next season I will play in the People's Theater...

Hearing such a thing, {{< var boris >}} began to equivocate. He said that this is impossible because I would have to be a member of the {{< var hau >}}. When I suggested they could use their influence to get me admitted to the union, {{< var edelstein >}} said:

-- You'll see, you'll see, the main thing is to gird yourself and be strong, and know the right thing to say. {{< var Nu >}}, in short, we'll see to it that you will join the union... What then will we do with you in New York? How will we butter you up?

We then got around to talking about my price to play for one season in the "People's Music Hall." We agreed that I would receive $35 a week, and my wife would receive $15 a week. And when they asked how much I would like to receive a week to play the next season in People's Theater with {{< var thomash >}} and {{< var adler >}}, I really didn't know how to answer. I knew that to play in People's Theater, I couldn't ask for more than I was getting in People's Music Hall. ^[This sentence is particularly blurry, translation may not be accurate.]The thing was, if I asked for the right amount of money, then the chances of earning more would be better later. So, with a considerable amount of uncertainty, I hedged:

-- Well,...How about $20 a week?

With this, {{< var edelstein-full >}} looked at me as though I had asked for far too much. That's how it seemed to me. But he had something completely different in mind. He leaned his head on his shoulders, as he used to do when he had to give some kind of firm decision that he stood resolute on, he said:

-- Get out of here, you imbecile! You won't be able make a living on $20 a week; I'll give you $30...

I then did not believe my own ears; This was the first time that I saw the ever-sullen {{< var edelstein >}} show someone genuine kindness and treat them so considerately. Later, when I got to know {{< var edelstein >}} better, I saw that, through his gloomy demeanor, he was really a very good person. He could do favors quietly and he never made a big deal out of it. Besides, he was a man of his word, and if he promised you something, you could rely on it. You could always count on his word.

I then proudly told everyone that {{< var edelstein >}} had hired me, and when I left for New York after the season in Philadelphia, I settled there with my family. And I was sure that now that it's finally come true, my dream to play Yiddish theater in New York, and everything would finally be good. But if course it didn't go as well as I had imagined. A lot of great difficulties were still in store for me. Quite a lot indeed.

