# December 12th, 1946

_This article is not available from the National Library of Israel. The article was obtained from the New York Public Library's microfiche archives._

> The music halls of yesteryear - The atmosphere of pub and theater plays. - "Yes" and "No" in the {{< var hau >}}.


Before I tell you further about the new turn of events that my life on took on the Yiddish stage after I settled in New York, it's necessary to talk a little bit about the Yiddish music halls, which were then very much in vogue. This is a separate chapter all on its own, so it's worth mentioning a few things that have long been forgotten.

In the year that {{< var edelstein >}} and {{< var thomash >}} brought me down to New York to play in the People's Music Hall, there were no more than four Yiddish theaters where plays were performed. But there was an abudance of music halls, or "Yiddish varieties" as they were called then. In that one year, ten or twelve music clubs opened. In them, sitting at a litle table and drinking a glass of beer, you could listen to Yiddish songs couplets, or you could watch dramatic one-act plays or sketches, which caught out of nowhere andw were quickly played in such a way that every time they played they had a different face, because it was very unexpected to approach, he added and what a phrase it is It occurred to him to see, he said...
This music halls was very popular with the general public, and this was no wonder, because they played and sang in such a way as to suit the taste of the crowd, and quite a few songs were from that group. ..., which have certain hints; The tickets were cheap, you could get in there whenever you wanted, you could drink as much beer as you wanted, and when you weren't sober enough, you could afford the pleasure of singing with your voice together with the actors on stage and it was lively and cheerful.
All around, there was such an atmosphere in that music hall that it was a kind of combination of a pub and a theater play, and the Yiddish theater had to compete with them and the competition had to be taken very seriously, because the crowd was very happy and they had fun and enjoyed themselves.
