# December 26th, 1946

_This article is not available from the National Library of Israel. The article was obtained from the New York Public Library's microfiche archives._


> How the "Professor" {{< var m-horowitz >}} wrote a play. -- His operetta **{{< var yiziat >}}**. --  An interesting story about a song about [{{< var moses >}}'s^[Moses] staff](https://en.wikipedia.org/wiki/Staff_of_Moses).

The messenger who came to tell me that {{< var horowitz-full >}}, the "Professor" himself as he was called, wanted to see me was [{{< var shor-full >}}](https://www.museumoffamilyhistory.com/yt/lex/S/schorr-anshel.htm). And as usual, he behaved as though this whole matter was a secret that should be kept from the whole world.

He was still a {{< var griner >}}^[A greenhorn; naive new immigrant], {{< var shor-full >}}, very energetic and very skilled. But he quickly caught on and adapted to the American ways, so they called him "the yellow {{< var griner >}}." {{< var heine >}} gave him the name, and it stuck.

In the Windsor Theater, {{< var shor-full >}} was the "Professor"'s right hand man, and he attended to everything the "Professor" needed. When a song needed to be written, he wrote a song, and when a scene needed to be staged, he staged a scene. And on top of this, he understood the audience well and knew what they wanted.

All in all, {{< var shor-full >}} already had the makings of a "Theatrical Bismarck," as he was later called, and everything he did made it seem like he really had a firm grasp on all the politics one needed to know.

It goes without saying that I didn't play hard to get, and I went to the Windsor Theater to see the "Professor" {{< var horowitz-full >}} at the requested time. And when he saw me, he immediately got to the point:

-- Hear me out - he said like it was an order - I've heard, as they tell me, that in People's Theater they pay you thirty dollars a week. {{< var Nu >}}, I will pay you forty dollars a week if you sign with me to play here with us in Windsor Theater next season.

And I immediately signed right there on the spot, and it was settled that I would play with Windsor Theater for the whole next year.

I didn't need to make a secret out of it. I let the managers of the People's Theater know right away that next season I had decided to join the "Professor"'s troupe in the Windsor Theater. They were happy for me, or at least that's how it seemed to me. But {{< var edelstein >}} was upset that I didn't tell him earlier I was thinking of leaving. And let me say, this was not unreasonable; I should have told him about it earlier, because he had always really stood up for me and treated me very well. But the deal had been made, and there was no going back. And I was really looking forward to it too. I had to get out of the situation I was stuck in in the People's Theater where I never got the opportunities I wanted because {{< var bessie >}} was always playing in pants and getting all the roles that, in my opinion, I was better suited for...

The truth was, in those days the "Professor" {{< var horowitz-full >}}'s career was heading downhill, and his plays which he quickly threw together like he was baking fresh buns were not as well-received as they used to be. New winds had started to blow in the Yiddish theater.Audiences were developing more sophisticated tastes, and the leading actors had a strong interest in playing better roles. The historical and non-historical operettas that the "Professor" churned out looked more and more ridiculous. But the "Professor", he was still very impressed with himself and still acted like a wealthy prince, a great magnate, throwing money around left and right.

Indeed, while signing the deal with me, he felt generous and gave me several hundred dollars on the spot for me to live on over the summer, because I wasn't able to put much away from the thirty dollars a week I was getting from the People's Theater^[Recall he was also supporting three children: Freddie, Lillie (my great-grandmother), and Louie].

And when I showed up to rehearsals at the Windsor Theater at the end of the summer, we were told that the new play the "Professor" had written was something like no one in America had ever seen before. There was no doubt that it would be a great success - so successful that the other theater managers would eat themselves alive with jealousy...

The new play was a historical operetta called {{< var yiziat >}}, and actors cast in the play included [{{< var blank-full >}}](https://www.museumoffamilyhistory.com/yt/lex/B/blank-leon.htm), [{{< var juvelier-full >}}](https://www.museumoffamilyhistory.com/yt/lex/J/juvelier-kalmen.htm), [{{< var shrage >}}](https://www.museumoffamilyhistory.com/yt/lex/S/shrage-adolph.htm), and many more other famous actors. And [{{< var dora-full >}}](https://www.museumoffamilyhistory.com/yt/lex/W/weissman-dora.htm)^[She would later marry {{< var shor-full >}}], the daughter of the well-known [{{< var reuben-weissman >}}](https://www.museumoffamilyhistory.com/yt/lex/W/weissman-reuben.htm) who was considered the most intelligent man in the theater world, was cast in the female roles.

She was young and beautiful then, the talented actress {{< var dora-full >}}. On top of that, in the Yiddish theater she was someone who was known as a "product of America." When she came to America with her parents from Odessa, she was no more than two or maybe three years old, she was educated in America schools, and she knew the American stage well because she never failed to miss seeing an English play. More than anything, she loved musical comedies with singing and dancing. She was good-natured, and she danced beautifully, like a real classically-trained actress who acts in musical theater, and in the operetta {{< var yiziat >}}, which was supposed to be something of a musical comedy, she was given the role of an Egyptian princess in Pharaoh's court. The role was written so that she would have dancing and singing parts.

They also made sure that I too would be able to sing and dance in this historical operetta. I was given the role of an Egyptian prince who was also in Pharaoh's court, the same Pharaoh who forced the Jews into slavery to build [Pithom and Rameses](https://en.wikipedia.org/wiki/Pithom#Biblical_Pithom)^[Cities which the ancient Israelites were, according the Bible, forced to build while enslaved in Egypt]. This role was written so that the audiences wouldn't think ill of the prince, indeed the opposite, because in the end of the play, he would suddenly become a true friend of the Jewish people and go with the Jews out of Egypt, along with the princess played by {{< var dora-full >}}. Both of us, as a couple, would sing and dance together. At rehearsals, the "Professor" himself said to us that we had to do this together, so that all of New York would lose their minds.

-- It has to really be something, something there has never been before until now! - as the "Professor" would say to us in his {{< var daytshmerish >}}^[[Germanified Yiddish](https://forward.com/culture/127096/daytshmer-nightshmare/) generally used in early Yiddish theater to make Yiddish more sophisticated.]...

Just like {{< var dora-full >}}, I was also a huge lover of musical comedies that were performed in English. I never missed a musical comedy performance on the American English stage, and I had always enjoyed how they danced together, as a couple, both following the same rhythm and harmony. Together, {{< var dora-full >}} and I studied a dance like this, a dance just like they did in a good musical comedy on the American stage. This was something really new for the Yiddish theater, a big todo, because in general, this sort of thing was not done on the Yiddish stage. This sort of thing was not even considered. It was looked upon as though it was in real life - when men and women danced, the man should dance to one rhythm while the woman should dance to another.

Even the great artist {{< var mogu >}} didn't do such things. Even as he spoke and sang and danced with a world of rhythm, he would go along with one rhythm, and others would go along with another rhythm... With his great talent, {{< var mogu >}} could do anything, but others couldn't, and therefore it always looked ridiculous to see two people dancing to completely unrelated rhythms on stage at the same time.

While rehearsing our dance, {{< var dora-full >}} and I were very pleased that we had the genius idea to bring such a good thing^[dancing together] from the American to the Yiddish stage. And when everyone saw how we were dancing together as a couple, we were sure it would be a big success because it was something new which had never been seen before on the Yiddish stage.

We impatiently looked forward to our first performance. During rehearsals for {{< var yiziat >}} - a play that was supposed to "conquer the world" - we had a lot of {{< var tsures >}} because we could tell that even though the "Professor" said he had already written the whole piece, were always missing a few pages here and there that he was still wrapping up. I remember once how in the middle of rehearsals, we suddenly came to a scene that just ended in the middle, and if this scene wasn't completed, we wouldn't be able to proceed because the audiences definitely would not understand what was happening. The "Professor" furrowed his brow, and he said something that nobody understood at first because we had no idea what he meant by it:

-- Aha! - he exclaimed - The stick!

What stick, who stick?...he didn't say. Only later did we catch on to what he meant - he meant that he needed, right there on the spot, to write a song about the staff that {{< var moses >}} used to perform miracles when he confronted the Pharaoh and later used to part the Red Sea... The song about the staff will take the place of the scene that he should have written, but of course did not write, and I would sing the song... Me - in the role of an Egyptian prince who began as an enemy of the Jewish people but later became their friend and leaves Egypt with them guided by {{< var moses >}} to the land of Canaan, the land where milk and honey flows and goats graze on carobs as much as grass...

And indeed right there on the spot, the "Professor" {{< var horowitz-full >}} called over the theater's two musical directors - [{{< var wohl-full >}}](https://www.museumoffamilyhistory.com/yt/lex/W/wohl-herman.htm) and [{{< var perlmutter-full >}}](https://www.museumoffamilyhistory.com/yt/lex/P/perlmutter-arnold.htm)^[It's worth nothing that Sam gives his name here as _Ephrim_ {{< var perlmutter >}}, not Arnold. Notably, in {{< var wohl >}}'s Leksikon entry, he is _also_ referred to as Efrim. So, it very possible like this was indeed his {{< var haimishe >}} name and his good friends did not call him Arnold, his American-adopted name.], as well as {{< var shor-full >}} - and he gave them an order:

-- You, {{< var anshel >}}, write this song right away, the song about the stick. You write the words, and you two - he pointed to {{< var wohl >}} and {{< var perlmutter >}} - go write the music...

And so they did...^[The song was called _Der Shteken_. You can find the [sheet music here](https://www.loc.gov/resource/ihas.200154899.0/?sp=8&st=image) and the [full lyrics (which indicate "as given by Mr. Kestin") here](https://www.loc.gov/resource/ihas.200185574.0/?sp=9)].

{{< var shor-full >}} wrote and erased, erased and wrote, added a rhyme, removed a rhyme. {{< var wohl >}} and {{< var perlmutter >}} also, in their own way, wrote and erased, erased and wrote, trying out different notes on the piano. The sweat was pouring out of all three of them, all working hurriedly to write a song they hadn't ever thought about before. And when the finished writing the song about {{< var moses >}}'s staff, the "Professor," with a pleased smile on his face, said:

-- This will work and it will go well...

The whole way of rehearsing in the Windsor Theater, where we had to wait for the "Professor" to hand out pages here and there from operetta {{< var yiziat >}} was something entirely unusual. Everyone was really exasperated but at the same time cracked jokes about it and laughed about it. But I haven't even told you the best part yet - I'll tell you about it in the next chapter...
