# January 11th, 1947

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1947/01/11/01/)_ {.unnumbered}

> Good and bad moments while playing together with {{< var kessler-full >}}. -- Character traits of the great artist.

During the rehearsals that {{< var kessler-full >}} held in Brooklyn's Lyric Theater when we were putting on {{< var gorky >}}'s play, {{< var kessler >}} was harder on {{< var schwartz >}}^[{{< var schwartz-full >}}] than on than anyone else. {{< var kessler >}} would always single him out, and whatever {{< var schwartz >}} did, {{< var kessler >}} was not pleased with it and scowled at him, 

-- Not like that!...

This was {{< var kessler-full >}}'s nature: During rehearsals, he would berate^[torture, torment] the good actors more than the others. And if you asked him why he never did this with the established actors who, in reality, had barely a crumb of talent, he would answer:

-- And if I say this to him, will it help us?...I wouldn't get anything more out of him either way... But I'll get a lot more from an actor with talent...

In those rehearsals, he made {{< var schwartz >}} so depressed that it was no wonder that {{< var schwartz >}} really took it to heart, and a day before the performance he told us that he wasn't able to perform because he didn't feel well. So they gave his role to {{< var simonoff >}}, and {{< var kessler >}} didn't say anything to him but just let him perform the role however he wanted...

Only when {{< var kessler >}} had the chance to put on a better piece written by a good dramatist was he delighted - it was like a {{< var yontif >}} for him. But not so for the bad pieces; he used to say that having to recite the lines the Professor^[recall, Professor {{< var horowitz-full >}} wrote {{< var shund >}} plays] wrote was just like chewing [oakum](https://en.wikipedia.org/wiki/Oakum). When performing these kinds of plays, he would make fun of everyone's role - and indeed his own role too - and there was such confusion on stage that nobody knew what on earth he was doing...
