# February 1st, 1947

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1947/02/01/01/)_ {.unnumbered}

> When {{< var mogu >}} was ill, he came to Philadelphia to play in my benefit performance. -- A scene that took place behind the curtain that can't be forgotten.

When it was announced around Philadelphia that {{< var mogu >}} will appear in {{< var greenhorns >}} in Arch Street Theater, all the tickets were bought up in a mere three days time. The announcements were big and bold, and read:

-- The greatest three comedians of the Yiddish stage - {{< var mogu-full >}}, Sam Kestin, and {{< var frank-full >}} - in one performance."

They did need to say anything more than that. The rush for tickets was so great, that if there were more room in the theater, three times as many could have been sold. {{< var Nu >}}, it goes without saying that I felt like I was in seventh heaven, and I was thankful to {{< var mogu >}} with all my heart for not turning me down. In the letter which I wrote him at the time, I relayed how the audiences in Philadelphia were eagerly expecting him, and he could be sure that he would receive such an ovation in the theater that he'd never forget for the rest of his life. Everyone was talking about the performance, and everyone was looking forward to seeing {{< var mogu >}}.

But exactly one day before the performance, I received a telegram from New York that {{< var mogu >}} had again fallen seriously ill and is unable to speak, and therefore he would not be able to come to the performance. 

When I read over the telegram, my eyes went dark. At first I suspected that {{< var molly >}} had made this up so that he wouldn't have to come perform. But soon I dismissed this suspicion because I knew that {{< var mogu >}} really was ill, and it was nothing new that he lost his speech and couldn't utter even one word.

There was no time to lose. The thought that when audiences found out that {{< var mogu >}} would not be coming they'd tear me to shreds had me unable to stay calm. And since I knew that back in New York, {{< var mogu >}} was under the care of {{< var held >}}- the brother of [Adolph Held](https://en.wikipedia.org/wiki/Adolph_Held), who was at that time, as I recall, the business manager of the {{< var forverts >}}, I straight away sent a telegram to {{< var held >}} that even if {{< var mogu >}} is unable to perform, would he allow him to come to Philadelphia just to present himself to the audiences, since this would surely save me. If not, {{< var khalilah >}}, I would be doomed and I would be simply ashamed to show my face in public again. 

I was really rattled over this, pacing around unsettled and disconcerted. And to this day, I can't forget how I rejoiced when I saw {{< var mogu >}} the next day. He didn't come to Philadelphia by himself, but together with {{< var molly >}} and {{< var held >}}. The good doctor, who had always held the talents of the great actors of the Yiddish theater in high regard, did not want to let {{< var mogu >}} travel to Philadelphia alone, so he therefore came with him. 

In my great joy, I took them to a hotel, but from the way {{< var mogu >}} looked and from the few words that he managed to utter, it was clear that he certainly wasn't able to perform. It broke your heart to see him that way. I reassured him as much as I could - I thanked him for coming, and I told him that he doesn't need to perform. It's enough for him to just present himself on the stage so the audiences can see that he was there, but he was not in good health, and it was difficult for him to talk, so he would not perform. 

But he was stubborn:

-- What do you mean that I will not perform?! I will too perform! 

He turned and beseeched {{< var held >}}:

-- Doctor, let me perform! I gave him my word...

{{< var held >}} had no great desire to grant him permission to perform that evening. This was plain to see. {{< var molly >}} also really did not want him to perform that evening either, and this too was plain to see. But {{< var mogu >}} begged and begged until the doctor gave in:

-- Well... What can we do, what?... You can perform, but remember: don't exert yourself too much...

And you just had to see how {{< var mogu >}} rejoiced when he heard this. He rejoiced like a child.

It was difficult for him to perform. In the first few scenes, he was so quiet that you could barely hear what he was saying. But out of respect for him, the audience didn't think of such a thing as to demand that {{< var mogu >}} speak up. They understood that his illness was what made his voice was so soft.

But after he had played the first few scenes, a miracle suddenly happened and he perked up, and he began to speak so that everyone in the theater could hear what he said. The audience was so overjoyed that the whole theater resounded with applause. They heard {{< var mogu >}}'s voice, his beloved voice, which always charmed the audiences so, and they rejoiced. 

The actors on the stage were also thrilled. 

{{< var mogu >}} speaks!

You could hear his voice now! You could hear it!

He proceeded to play the whole rest of his role such that, every gesture and every movement and every sparkle of his eye evoked enthusiasm from the audience. When the curtain fell, the theater was simply full of screams which for years and years had been heard across Yiddish theaters in Russia, Romania, and many other countries:

-- Bravo, {{< var mogu >}}! Bravo, {{< var mogu >}}!

But after the performance he was terribly exhausted. Sweating profusely, he sat still and didn't say a word. {{< var molly >}} sat next to him, and just like him, she also didn't say a word. She only looked at him, and in her eyes you could see an ocean of pity. 

I walked over to him, and I'm not ashamed to say now that my eyes were filled with tears.

-- {{< var Nu >}}?! - He said to me, with a smile. -  {{< var Nu >}}?!

I didn't know what he meant by this. But maybe he meant:

-- {{< var Nu >}}, you see, when {{< var mogu >}} promises something, he keeps his word and you can rely on him... 

But I wasn't able to think much about what he meant by "{{< var Nu >}}," and taking out a hundred dollar bill from my pocket, I said to him:

-- Listen, my dear friend! I don't have much to give to thank you for what you have done for me. I will never in my whole life forget this. But you have to take this hundred. I beg you, take it. It is from the bottom of my heart. 

{{< var molly >}} was thrilled and immediately grabbed the hundred to put it away. But when {{< var mogu >}} saw this, he frowned. You could tell that he was uncomfortable with the whole situation, and with a pleading voice he said to {{< var molly >}}:

-- {{< var molly >}}, give him back the hundred! You heard what I said, {{< var molly >}}? Give him back the hundred!...

She had no desire to obey him, and looking right at me and then at him, she started talking about what a sick man he was, such a sick man, and he needs to be looked after. With this, she obviously wanted to calm him down and remind him that now, as always, he must also follow her lead and not interfere in matters that he doesn't understand. But this time he was insistent and he held firm:

-- {{< var molly >}}, give him back the hundred! You heard what I said, {{< var molly >}}? Give him back the hundred!... I will be ashamed to look him straight in the eyes if you take that hundred from him ... He didn't force me to play at all, so I won't take anything from him...

And when he saw that she was still not willing to give the money back, he became angry:

-- {{< var molly >}}, give him back the hundred dollars already!

This was the first and only time I ever saw {{< var mogu >}} get angry with his wife {{< var molly >}}.

No matter how muched I begged him to take the money, I couldn't prevail upon him. And when I said to him, how about the next morning I come pick him up from his hotel in an automobile and "take him out" a little to show him around the city along with {{< var molly >}} and {{< var held >}} and treat them to a nice meal in a fancy restaurant, he answered me with a smile and said that this he simply could not refuse, and I should come to his hotel the next morning no earlier than 11 o'clock. 

But when I arrived at his hotel the next morning at the agreed upon time, I was told that Mr. {{< var mogu >}} had already left two hours earlier...

He had known when he would leave, and therefore he had intentionally told me to come later. When I later saw him back in New York, I complained to him that he didn't wait for me. With a smile, he asked me, 

-- Come on now, is spending your money on me really how you want to go through life?

He didn't want me to spend any money on him. It was his pleasure to do such a huge {{< var toive >}}, and this made us completely even^[Sam saved {{< var mogu >}}'s benefit performance, and {{< var mogu >}} saved his.]. Everything was clean, without even the slightest stain. His artistic soul could not bear a stain between friends.
