# February 6th, 1947

##### _Link to [{{< var forverts >}}](https://www.nli.org.il/en/newspapers/frw/1947/02/06/01/)_ {.unnumbered}

> A leap from light comedies and merry operettas to serious dramas. --  The sad end of the great artist {{< var mogu >}} and the legacy he left behind.

Of all the Yiddish actresses who found themselves going through a big or small family tragedy or who had to deal with infidelity, {{< var bessie >}} stood out from the very beginning. Not only her friends but also her enemies had to admit that, just like an independent man, she too was an independent woman, and her career on the stage didn't depend on any man.

When she stood on her own two legs after parting ways with {{< var boris >}}, her comedy {{< var khantshe >}} made such a splash that she became a brand of her own. Whenever business was going poorly in one theater or another and they needed some major attraction to bring cash into the box office, they brought in {{< var bessie >}} to put on {{< var khantshe >}} with her troupe, and they brought in a lot of money.

Even the National Theater, where {{< var boris >}} played with his troupe, brought in {{< var bessie >}} to perform {{< var khantshe >}} at the end of the 1913 season^[Specifically, May 30th - June 1st 1913 [(Source)](https://www.nli.org.il/en/newspapers/frw/1913/05/26/01/article/16.1)]. For her, this was of course a great triumph because it meant that business in the National Theater without her wasn't as good as it used to be. And it didn't matter if that was really true or not. The main point was that's how it was interpreted.

[{{< var goldberg-full >}}](https://www.museumoffamilyhistory.com/yt/lex/G/goldberg-louie.htm), the manager of the National Theater at that time, engaged {{< var bessie >}} to play {{< var khantshe >}} for no more than a week. {{< var thomash >}} himself wasn't involved. He wasn't in town at all at that time, because he had run off somewhere with {{< var regina >}}. In the theater circles, people said that the love between them was so great that a very interesting novel could be written about it.

Many young Yiddish actresses were jealous of the prima donna {{< var regina >}} because {{< var thomash >}} had a generous hand - he conducted himself like a magnate, and money was no object for him. In awe, people told of the expensive gifts he bought for her, how he doted on her, and how he would do anything in the world for her. And along with their jealousy, they also slandered her. When someone caught wind of some gossip or slander, they brought it straight to {{< var bessie >}} as if they wanted to show her what a good friend they were.

The sworn flatterers no longer flattered her as the wife of a star, but indeed as a star in her own right because {{< var bessie-first >}} had emerged as a self-made independent star herself.

{{< var bessie >}} was paid very well during the week she was engaged to play in {{< var thomash >}}'s National Theater - she made a lot of money in that one week alone. The income at the box office itself was huge, and this made the talented actress so pleased that she forgot about her grievances and the wrongs done to her, and she was really in seventh heaven. Triumphantly, she told to her close friends - "You see, they're not coming to see the prima donna {{< var regina >}} in {{< var thomash >}}'s theater - they're coming to see {{< var bessie >}}."

So, we put on the comedy {{< var khantshe >}}. When {{< var goldberg-full >}} saw me in the role of the elevator man, he wrote a letter to {{< var thomash >}} saying that, in his opinion, they shouldn't let me go at the end of the run but they should hire me to play in the National Theater for the next season. He told me this himself, and we signed a contract for me to play in {{< var thomash >}}'s National Theater during the 1913/1914 season.

{{< var boris >}} started the next season with a bang. In addition to the prima donna {{< var regina >}}, he hired two more prima donnas, and he hastily wrote a new operetta called {{< var sheep >}}, and he hired the two composers {{< var perlmutter >}} and {{< var wohl >}} to write the music.

They went all out for this show, including something entirely brand new - they build a bridge, a long bridge, that stretched all the way from the stage to the theater exit. And on this bridge was a choir with young women, with me between them leading all the "{{< var tsoyn-kodoshim >}}"^[According to the dictionary, "an often humorous appellation for young Jewish children, or the Jewish people as a whole"] over the long, narrow bridge. Such a thing was "not done," as we said in our theater dialect.

It was thought that all the bells and whistles like this in {{< var sheep >}} would make the show a big hit with audiences, and the show would of course play for the entire season and we'd make "golden business" with it. But audiences weren't impressed at all. {{< var sheep >}}, {{< var nebech >}}, was a failure. Afterwards, we tried to put on other new operettas, all written hastily by {{< var thomash >}}, and we put them on just as hastily as he wrote them. Each time, people thought that _this one_ would surely be the one to have great success, but they were all failures, and we really didn't know what to do next.

It seemed that {{< var thomash >}} had suddenly lost all of his luck. In the theater {{< var kibitzarnie >}}^[bar/cafe where one goes to {{< var kibitz >}} (gossip, banter)], people cracked jokes at his expense, and made wisecracks that there was only one person who could save him now - {{< var bessie >}}.

And {{< var bessie-first >}} was filled with joy when she learned about these jokes.

As it usually went in the Yiddish theater when things weren't going well, we threw ourselves from one extreme to another - no longer playing operettas with all their "dances or marches," as was the style in those times, we bought {{< var asch-full >}}'s serious literary drama {{< var gloybn >}}. With the full certainty that _this one_ would of course bring us great success and would attract a large audience, roles were quickly handed out, rehearsals were held, and before we knew it, we put on {{< var asch >}}'s piece. I remember that at first, I was not given a role in this play, but when I complained and demanded that I too be given a role to play in {{< var asch >}}'s piece, {{< var thomash >}} gave me some small role of one of the in-laws, and the critics greatly praised my performance.

Because my role was so well regarded, I really wanted the piece to be a huge success and play for a long time. But the piece as a whole was not a big hit with Jewish audiences. It was a huge failure and only ran for a short time.

{{< var asch-full >}}'s piece {{< var gloybn >}} was a powerful one, but it was constructed in such a way that, willy-nilly, the {{< var goyishe >}} characters were very sympathetic, but the Jewish characters were not. As I recall, the play was about a Jewish girl who falls in love with a {{< var sheygets >}}^[a gentile boy; male equivalent of _shiksa_] and converts to Christianity and marries him. Trouble arises when she requests that her Jewish mother and father come to see her; she wants to see them while she is in labor, a very difficult labor, and she is sure that if they don't come, she'll die of heartache. But the converted daughter's parents will not go to her, even when the {{< var goyishe >}} in-laws go to them and implore them to show mercy and compassion and save their own daughter - their own flesh and blood - from death. But they show no mercy and do not go to her, and she dies of heartache and resentment.

That is the "essence" of the drama, as it is etched in my memory. And it could be that because the {{< var goyim >}} were sympathetic characters but the Jewish ones were not, Jewish audiences found it unpleasant, and the play was a failure.

It was in the 1914 season that {{< var mogu >}} passed away.

He died [on the 4th of February 1914](https://www.nli.org.il/en/newspapers/frw/1914/02/04/01/article/2/). His last residence in New York was a furnished room on a side street off of Second Avenue. This was the "home" of the great Yiddish artist who even to this day has no equal on the Yiddish stage. He could not afford a better home because over the course of his illness which drained him so thoroughly, he had to be judicious with his expenditures because, as I've already told you, annual benefit performances were his only source of income.

He was 56 years old when he died. And up until the last minute of his life, he had full cognitive function. He knew that he was dying. He often talked to me about it when I would visit him on his deathbed. And here, I want to mention what they said in the theater circles after his death about his relationship with me and his opinion of me: It was said that when he was once asked which comedian on the Yiddish stage should be his legacy and take over his roles, he answered that the only Yiddish comedian who he would leave his roles and legacy to was {{< var sam-full >}}, and no other.

That's what they said.

And as long as I live, I will not forget the pleasure that I had every time I saw him in his roles, and every time I played together with him on the stage.

It was an honor to know {{< var mogu >}} and be his friend. It was an honor for a Yiddish actor to live in the same generation as {{< var mogu >}}.

Even now, we have never had an artist as great as {{< var mogu >}} on our Yiddish stage.

May his name ever remain among us!
זאָל זיין נאָמען אויף אייביק בלײַבן צווישען אונז!