# February 6th, 1947

##### _Link to [Forverts edition](https://www.nli.org.il/en/newspapers/frw/1947/02/08/01/)_ {.unnumbered}

> {{< var a-shomer >}}'s {{< var griner-m >}}. -- Compliments from {{< var sholem-a >}}. {{< var boris >}}, {{< var blank-full >}}, and [{{< var gershon-full >}}](https://www.museumoffamilyhistory.com/yt/lex/R/rubin-gershon.htm)

At {{< var thomash >}}'s theater, you never knew what role you'd be cast in in a week's time, or even tomorrow. {{< var thomash >}} never stuck to one style of play - When operettas, where dances, marches, and songs were the main point of the show, didn't go well, he would instead put on a serious drama. And if the serious drama wasn't successful, he immediately reversed course and went back to putting on operettas. 

So we got tossed back and forth from one kind of play to another, when we never knew what we'd end up doing next. And here I have to mention, that even though {{< var thomash >}} was considered an operatta-oriented actor, he very much excelled in serious roles too. He only had to will it, and he would play very well. The truth was that he had a good sense of realism when playing dramas. He could play them naturally and bring the characters to life. But as though he were possessed by some kind of [{{< var dybbuk >}}](https://en.wikipedia.org/wiki/Dybbuk), he was inclined to have a haughty and pompous tone, and he felt more at home in a foolish operetta than in a realisitic drama. 

But perhaps he just wanted to show that, in the theater, he was a "master of everything."

Among the plays in which {{< var thomash >}} excelled when I played with him over several seasons in the National Theater was {{< var a-shomer >}}'s distinguished comedy {{< var griner-m >}}. {{< var blank-full >}} and I were also exceptional in this play. And the interesting thing was that, hearing the comedy read aloud, {{< var thomash >}} wasn't impressed by it, and neither were other actors in the troupe. People were sure that it would be a huge failure. 

The only person who was certain that the comedy was sure to be a huge success was the author himself, {{< var a-shomer >}}, the son of the famous novelist {{< var schaik >}}, aka {{< var shomer >}}. He talked about his comedy with such enthusiasm that it infected us all. 

This was in the 1915 season, after a whole series of failures of other plays in the theater. And as usual in such moments, we were ready to try anything - even plays we didn't really believe would succeed. Everyone was simply tired of all the failures during the previous season. And when {{< var a-shomer >}} set the condition that he, not {{< var thomash >}} should direct the play himself, we of course let him take the reins. 

{{< var a-shomer >}} was really able to direct a play. He had a good understanding of the theater and a healthy sense of realism and performing with a natural tone. 