---
format:
  html:
    page-layout: full
---

# Appendix B: Glossery of plays {.unnumbered}

This appendix contains a table of Yiddish Theater plays that Sam mentions, either as a play he performed in, attended, or refers to someone else performing in.
Plays are listed in order of first appearance.

In the `Playwright/composer(s)` column, I provide names of those who were _documented_ to have been involved writing the play and/or music.
An absence of a composer or lyricist does not imply that the main playwright necessary also wrote the songs; in many cases, this information is just not definitively known (or I haven't found it yet!).
It was also common for songs to be added to plays by additional songwriters who were not officially credited.

| Play name                                            | English translation                                                                                   | Playwright/composer(s)                                                                                                                                                                                                                                       | Chapter(s)      | Synopses/scripts, where available                                                                                                                                                      |
| ---------------------------------------------------- | ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | --------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| {{< var shulamith >}}                                | _Shulamith_                                                                                           | {{< var goldfaden-full >}}                                                                                                                                                                                                                                   | 6, 7, 8, 20, 24 | [Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/shulamis-oder-bas-yerusholayim)                                                             |
| {{< var barkochba >}}                                | _Bar Kokhba_                                                                                          | {{< var goldfaden-full >}}                                                                                                                                                                                                                                   | 6, 20, 34       | [Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/bar-kokhba-der-zun-fun-di-shtern-oder-di-letste-teg-fun-yerusholayim)                       |
| {{< var coquettes >}}                                | _The Coquettish/Flirtacious Women_                                                                    | {{< var shomer >}}                                                                                                                                                                                                                                           | 7, 11           |                                                                                                                                                                                        |
| {{< var sorceress >}}_, oder _{{< var bobeyachne >}} | _The Sorceress_                                                                                       | {{< var goldfaden-full >}}                                                                                                                                                                                                                                   | 8, 11           | [Wikipedia](https://en.wikipedia.org/wiki/The_Sorceress_(play))<br>[Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/di-kishefmakherin)       |
| {{< var sailor >}}                                   | _Sailor in Peril_                                                                                     | Unknown English playwright; adapted to Yiddish by {{< var marx-full >}}                                                                                                                                                                                      | 9               |                                                                                                                                                                                        |
| {{< var honor >}}                                    | _Honor thy Father_                                                                                    | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 9               |                                                                                                                                                                                        |
| {{< var kuni >}}                                     | _The Two Kuni Lemels_                                                                                 | {{< var goldfaden-full >}}                                                                                                                                                                                                                                   | 10, 27          | [Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/di-tsvey-kuni-leml)                                                                         |
| {{< var yingl >}}                                    | _The Polish Boy_                                                                                      | {{< var horowitz-full >}}, based on the eponymous book by {{< var linetzky >}}                                                                                                                                                                               | 11, 32          |                                                                                                                                                                                        |
| {{< var alilesdam-full >}}                           | _Blood Libel, or Menachem Ben-Israel_                                                                 | {{< var boris >}}                                                                                                                                                                                                                                            | 11              |                                                                                                                                                                                        |
| {{< var velvel >}}                                   | _The Female Pioneer, or Velvele Eats Compote_[^tzimmes]                                               | Adapted by {{< var boris >}} from the eponymous play by [Simeon Bekerman](https://www.museumoffamilyhistory.com/yt/lex/B/bekerman-simeon.htm)                                                                                                                | 11              |                                                                                                                                                                                        |
| {{< var esther_eingedi >}}                           | _Esther of Ein-Gedi_                                                                                  | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 12              |                                                                                                                                                                                        |
| {{< var haim >}}                                     | _Chaim in America_                                                                                    | {{< var marx-full >}}                                                                                                                                                                                                                                        | 12              |                                                                                                                                                                                        |
| {{< var lostsoul >}}                                 | _The Lost/Wandering Soul_                                                                             | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 13              |                                                                                                                                                                                        |
| {{< var meilitz-long >}}                             | _Advocate, or Rabbi Yosselman_                                                                        | {{< var goldfaden-full >}}                                                                                                                                                                                                                                   | 14, 15          |                                                                                                                                                                                        |
| {{< var bowery >}}                                   | _The Bowery Tramp_                                                                                    | {{< var marx-full >}}                                                                                                                                                                                                                                        | 15              |                                                                                                                                                                                        |
| {{< var rachel-leah>}}                               | _Rachel and Leah_                                                                                     | _Unknown_                                                                                                                                                                                                                                                    | 15              |                                                                                                                                                                                        |
| {{< var kinglear >}}                                 | _The Yiddish King Lear_                                                                               | {{< var gordin-full >}}                                                                                                                                                                                                                                      | 15, 19          | [Wikipedia](https://en.wikipedia.org/wiki/The_Yiddish_King_Lear)<br>[Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/plotting-yiddish-drama/der-yidisher-kenig-lir) |
| {{< var alexander-long >}}                           | _Alexander, or the Crown Prince of Jerusalem_                                                         | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 15              |                                                                                                                                                                                        |
| {{< var jewish-priest >}}                            | _The Jewish Priest_                                                                                   | {{< var gordin-full >}}                                                                                                                                                                                                                                      | 19              |                                                                                                                                                                                        |
| {{< var blimele-full >}}                             | _Blimele, the Pearl of Warsaw, or The Count and the Jew_                                              | {{< var lateiner-full >}}, music and lyrics by {{< var mogu-full >}} and arrangement by {{< var friedsell-full >}}                                                                                                                                           | 20              |                                                                                                                                                                                        |
| {{< var mirele-efros >}}                             | {{< var mirele-efros >}}                                                                              | {{< var gordin-full >}}                                                                                                                                                                                                                                      | 21              | [Wikipedia](https://en.wikipedia.org/wiki/Mirele_Efros)                                                                                                                                |
| {{< var kiddush-hashem >}}[^notasch]                 | _Kiddush Hashem, or The Jewish Minister_                                                              | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 21              |                                                                                                                                                                                        |
| {{< var medea >}}                                    | _Medea_                                                                                               | Originally written in [German by the playwright Franz Grillparzer](https://www.goodreads.com/en/book/show/2605133), adapted to Yiddish by {{< var gordin-full >}}                                                                                            | 21              | [Wikipedia](https://en.wikipedia.org/wiki/Medea_(Reimann)) article about a German opera adaptation (2010) of the same play                                                             |
| {{< var kol-nidre-full >}}                           | {{< var kol-nidre >}}_, or the [Crypto-Jews](https://en.wikipedia.org/wiki/Crypto-Judaism) of Madrid_ | Abraham Michael Sharkansky with music by {{< var friedsell-full >}}                                                                                                                                                                                          | 24              |                                                                                                                                                                                        |
| {{< var devil >}}                                    | _God, Man, and Devil_                                                                                 | {{< var gordin-full >}}                                                                                                                                                                                                                                      | 24              | [The English translation](https://shop.yiddishbookcenter.org/products/god-man-and-devil-yiddish-plays-in-translation)                                                                  |
| {{< var no587 >}}                                    | _Number 587, or Mother Sarah_                                                                         | {{< var feinman-full >}}                                                                                                                                                                                                                                     | 25              |                                                                                                                                                                                        |
| {{< var immigrant >}}[^immigrant]                    | _The Immigrants_                                                                                      | {{< var shomer >}}                                                                                                                                                                                                                                           | 27              |                                                                                                                                                                                        |
| {{< var tisa >}}                                     | _Tiszaeszlár_                                                                                         | {{< var horowitz-full >}}                                                                                                                                                                                                                                    | 30              |                                                                                                                                                                                        |
| {{< var yiziat >}}                                   | _Exodus from Egypt_                                                                                   | {{< var horowitz-full >}}, music by {{< var perlmutter >}} and {{< var wohl >}}                                                                                                                                                                              | 30, 31          |                                                                                                                                                                                        |
| {{< var sons-full >}}                                | _The Children of Israel, or The White and The Black Jews_                                             | {{< var horowitz-full >}}, music by {{< var perlmutter >}} and {{< var wohl >}}                                                                                                                                                                              | 31              |                                                                                                                                                                                        |
| {{< var ghetto >}}                                   | _East Side Ghetto_                                                                                    | {{< var kobrin-full >}}                                                                                                                                                                                                                                      | 31              |                                                                                                                                                                                        |
| {{< var helena >}}                                   | _Helena, or the Jewish Medea_                                                                         | {{< var libin-full >}}                                                                                                                                                                                                                                       | 31              |                                                                                                                                                                                        |
| {{< var sobi-full >}}                                | _Reb Leyb Sephardi, or The Jew in the Age of Sobietsky_                                               | {{< var horowitz-full >}}, music by {{< var perlmutter >}} and {{< var wohl >}} and lyrics by {{< var shor >}}                                                                                                                                               | 32              |                                                                                                                                                                                        |
| {{< var yerusha >}}                                  | _The Inheritance_                                                                                     | George (Gershon) Zeikin                                                                                                                                                                                                                                      | 32              |                                                                                                                                                                                        |
| {{< var be-a-mentsh >}}                              | _A Person Should Be a Mensch_                                                                         | {{< var shor-full >}} and Moishe {{< var shor >}}                                                                                                                                                                                                            | 33              |                                                                                                                                                                                        |
| {{< var wedding-day >}}                              | _The Wedding Day_                                                                                     | {{< var lateiner-full >}}, music by {{< var brody-full >}} and {{< var friedsell-full >}} and lyrics by {{< var smulo >}}, but at least one song had music by [Otto Motzan](https://en.wikipedia.org/wiki/Otto_Motzan) and lyrics by {{< var gilrod-full >}} | 33              |                                                                                                                                                                                        |
| {{< var mayn-vaybs-man-full >}}                      | _My Wife's Man, or The Bigamist_                                                                      | {{< var meisel-full >}}, music by {{< var brody-full >}} and {{< var friedsell-full >}}                                                                                                                                                                      | 34              |                                                                                                                                                                                        |
| {{< var two-cantors >}}                              | _Two Cantors_                                                                                         | {{< var kalmano-full >}}, adapted by {{< var boris >}} with music by {{< var wohl-full >}} and {{< var gilrod-full >}}                                                                                                                                       | 35              |                                                                                                                                                                                        |
| {{< var vengeance >}}                                | _God of Vengeance_                                                                                    | {{< var asch-full >}}                                                                                                                                                                                                                                        | 36              | [Digital Yiddish Theater Project](https://web.uwm.edu/yiddish-stage/10-things-you-need-to-know-about-god-of-vengeance)                                                                 |
| {{< var maziq >}}                                    | _The Reformed Convict_                                                                                | {{< var a-shomer >}}                                                                                                                                                                                                                                         | 36              |                                                                                                                                                                                        |
| {{< var kreuzer >}}                                  | _The Kreutzer Sonata_                                                                                 | Adapted by {{< var gordin-full >}} for the Yiddish theater, based on the novella by Leo Tolstoy                                                                                                                                                              | 36              | [Wikipedia](https://en.wikipedia.org/wiki/The_Kreutzer_Sonata)                                                                                                                         |
| {{< var troubador >}}                                | _Zalmen Troubadour_                                                                                   | {{< var zolotkoff >}}                                                                                                                                                                                                                                        | 38              |                                                                                                                                                                                        |
| {{< var khantshe >}}                                 | _Khantshe in America_                                                                                 | {{< var rakov-full >}}, music by {{< var rumshinsky-full >}} and lyrics by {{< var lillian-full >}}                                                                                                                                                          | 38              |                                                                                                                                                                                        |
| {{< var greenhorns >}}[^greenhorns]                  | _The Greenhorns, or Mishke and Moshke_                                                                | {{< var lateiner-full >}}                                                                                                                                                                                                                                    | 39              | [Partial script, in Yiddish](https://www.yiddishbookcenter.org/collections/yiddish-books/spb-nybc212216/latteiner-joseph-mishke-un-moshke-oder)[^maybe]                                |
| {{< var sheep >}}                                    | _The Lost Little Sheep_                                                                               | {{< var thomash >}}, music by {{< var perlmutter >}} and {{< var wohl >}}                                                                                                                                                                                    | 41              | [Sheet music for the title song](https://www.loc.gov/item/2016767582/)                                                                                                                 |
| {{< var gloybn >}}                                   | _Our Beliefs_                                                                                           | {{< var asch-full >}}                                                                                                                                                                                                                                        | 41              |                                                                                                                                                                                        |
|                                                      |                                                                                                       |                                                                                                                                                                                                                                                              |                 |                                                                                                                                                                                        |
: {.striped .hover tbl-colwidths="[23,23,20,9,25]"}



<!-- turns out it is the female pioneer? [^divorce]: This is not quite an accurate translation. Instead, _Khalitse_ refers to the formal procedure that releases a man from the obligation of having to marry his brother's widow.-->
[^notasch]: Not to be confused with the [book of the same name by Sholem Asch](https://www.yiddishbookcenter.org/collections/yiddish-books/spb-nybc203723/asch-sholem-kidesh-hashem), which was later [adapted into a play](https://www.moyt.org/exhibitions/pih/kiddush-hashem.htm)
[^immigrant]: Not to be confused with the [book of the same name by {{< var kobrin-full >}}](https://yiddishkayt.org/view/kobrin/)
[^greenhorns]: Also known as _Mishke un Moshke, oder Eyropeyer in Amerike_ (_Mishke and Moshke, Europeans in America_)
[^maybe]: This might not actually be a partial script of this play. If it isn't, it's certainly a piece of related content.
[^tzimmes]: Noting I have also seen this referred to as _Dovid Velvele eats tzimmes_ ([Source](https://www.nli.org.il/en/newspapers/dwt/1913/04/30/01/article/62.3))