---
format:
  html:
    page-layout: full
---

# Appendix C: Timeline {.unnumbered}

This appendix contains a rough timeline (some dates are necessarily approximate, indicated with `~`) for Sam's whereabouts during the time periods the memoirs recount. 
Although Sam does not always mention it, based on historical records we know that his wife {{< var suzi >}} Kestin often performed in the same troupe with him through the early 1920s.

| Dates           | Location                                                                | Activity                                                                                                                                                                                                                                                                                                              | Chapter(s)   |
| --------------- | ----------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------ |
| 1869 -- ~1877   | {{< var zat >}}, Kiev Governorate, Russian Empire                       | Sam's early childhood in Ukraine, before his father's death                                                                                                                                                                                                                                                           | 1 -- 3       |
| ~1877 -- 1885/6 | {{< var rybinka >}}, Poltava Governorate, Russian Empire                | Sam's late childhood and early adolescence in Ukraine, after his father's death. <br> He experiences pogroms and witnesses a mob beat a young {{< var medvedev-full >}}. Sam arrives in America                                                                                                                       | 4 -- 5       |
| 1885/6 -- ~1887 | Philadelphia, PA                                                        | Sam sells parlor matches in Philadelphia and the "suburbs"                                                                                                                                                                                                                                                            | 5 -- 6       |
| ~1887           | Philadelphia, PA                                                        | Sam appears on stage for the first time as an extra in {{< var shulamith >}}, and he begins working as a tailor                                                                                                                                                                                                       | 6            |
| ~1887 -- ~1888  | Philadelphia, PA                                                        | Still working as a tailor, Sam meets {{< var mogu >}}                                                                                                                                                                                                                                                                 | 7            |
| ~1888 -- ~1889  | Philadelphia, PA                                                        | Sam performs for the first time in {{< var sorceress >}} in {{< var garten >}}'s troupe                                                                                                                                                                                                                               | 8            |
| ~1888 -- ~1890  | Philadelphia, PA and Bridgeton, NJ                                     | Sam performs in {{< var sailor >}}, and then briefly with the Thomashevsky troupe. <br> The Kestin family wins the lottery and buys a farm in the [Jewish Alliance Colony](https://en.wikipedia.org/wiki/Alliance_Colony)                                                                                             | 9            |
| ~1891 -- 1892   | Philadelphia, PA                                                        | Sam establishes and plays in the _Star Specialty Club_ troupe, where he meets {{< var suzi >}}                                                                                                                                                                                                                        | 10           |
| 1893 -- 1894    | Brownsville, Brooklyn, NY                                               | Sam plays in Parmer's Casino in Brooklyn.  <br> He marries {{< var suzi >}} and sells his farm to {{< var weinb-full >}}                                                                                                                                                                                              | 11 -- 12     |
| 1894 -- 1895    | Boston, MA                                                              | Sam joins {{< var abba-full >}}'s troupe and performs in Boston, where the young {{< var gest-full >}} is the theater errand boy. <br>He briefly returns to Brownsville for a small period during this time when things go poorly in Boston. <br> Sam performs with {{< var keni-full >}} in Boston in December 1895. | 13 -- 15     |
| 1895            | Baltimore, MD                                                           | Sam travels with the troupe to Baltimore, where there was a false-fire alarm and many were trampled to death around Christmas 1895. Sam quits the troupe over aftermath of the incident.                                                                                                                              | 15           |
| 1896 -- 1898    | Many cities, including Cleveland, OH; Pittsburgh, PA; and Buffalo, NY   | Sam travels the provinces acting with {{< var frank-full >}} and {{< var jakele-full >}}, and eventually rejoins {{< var schoen >}}'s troupe but of course leaves again because theater is a total mess these days.                                                                                                   | 16 -- 18     |
| 1898 -- 1899    | Cincinnati, OH                                                          | With his {{< var chevreh >}} {{< var frank-full >}} and {{< var jakele-full >}}, Sam acts in Cincinnati and gives {{< var clara-rafalo >}} one of her first roles                                                                                                                                                     | 18 -- 20     |
| 1899            | Many cities, including Louisville, KY; Cleveland, OH; and St. Louis, MO | Sam travels the provinces, changing troupes along the way. <br> He briefly travels to NYC to try and join {{< var boris >}} and {{< var jacob-adler >}}'s troupe, unsuccessfully. <br> In St. Louis, he meets {{< var gordin-full >}}                                                                                 | 21           |
| 1889 -- 1900    | Chicago, IL                                                             | Sam joins {{< var glickman-full >}}'s theater in Chicago where he again meets {{< var medvedev >}}. <br> Sam refuses to be a scab when asked to play in {{< var boris >}}'s theater during the strike in December 1889                                                                                                | 22           |
| 1900 -- 1901    | Philadelphia, PA                                                        | Sam joins {{< var ivan-abramson >}}'s troupe in Philadelphia at the Columbia Theater, after his first rejection from the {{< var hau >}} in New York. <br> Sam then joins {{< var mike >}}'s troupe in the Arch Street Theater <br> {{< var boris >}} and {{< var edelstein-full >}} invite Sam to act in New York    | 23 -- 24     |
| 1901 -- 1902    | New York City, NY                                                       | Sam^[And his wife, although he does not discuss her involvement specifically] performs vaudeville in the People's Music Hall during the 1901/1902 season. <br> At the beginning of the 1902 season, he is finally admitted to the {{< var hau >}}                                                                     | 25           |
| 1902 -- 1903    | New York City, NY                                                       | Sam performs in the People's Theater, managed by {{< var boris >}}, {{< var jacob-adler >}}, and {{< var edelstein-full >}}, during the 1902/1903 season. <br> Sam's timeline is somewhat out of order here; In Chapter 27, he recounts some stories from after he had moved on from the People's Theater             | 26 -- 27     |
| 1903 -- 1904    | New York City, NY                                                       | Sam performs in the Windsor Theater, managed by {{< var horowitz >}} and {{< var heine >}}, during the 1903/1904 season.                                                                                                                                                                                              | 28 -- 31     |
| 1904 -- 1905    | New York City, NY                                                       | Sam performs in the Grand Theater, managed by {{< var jacob-adler >}}, {{< var kessler-full >}}, and {{< var shpachner-full >}}, during the 1904/1905 season.                                                                                                                                                         | 31           |
| 1905 -- 1907    | New York City, NY                                                       | Sam performs in the {{< var kalich >}} Theater (formerly known as the Windsor Theater), managed by {{< var shpachner-full >}}, {{< var juvelier-full >}}, and {{< var feinman-full >}}, during the 1905/1906 and 1906/1907 seasons.                                                                                   | 32           |
| 1907 -- 1910    | Philadelphia, PA                                                        | Sam performs in Columbia Theater (and Arch Street Theater, although he does not specifically mention it), managed by {{< var mike >}}                                                                                                                                                                                 | 33           |
| 1910 -- 1911    | Brooklyn, NY                                                            | Sam performs in Lyric Theater (and other theaters where Kessler's troupe performed) in Brooklyn, NY, managed by {{< var kessler-full >}}, {{< var wilner-full >}}, and (?) Boaz (Bernard) Young                                                                                                                       | 33 -- 35     |
| 1911 -- 1912    | New York City, NY                                                       | Sam performs in the People's Theater, managed by {{< var boris >}} and {{< var edelstein-full >}}, during the 1911/1912 season                                                                                                                                                                                        | 36           |
| 1912 -- 1913    | Williamsburg, Brooklyn, NY and more                                     | Sam performs in the Novelty Theater, managed by {{< var sara-adler >}}, during the 1912/1913 season. The theater does not do well, so halfway through the season the cast is laid off, and Sam performs wherever he can                                                                                               | 37 -- 41     |
| 1913 -- 1920    | New York City, NY                                                       | Sam performs in the National Theater, managed by {{< var boris >}}, from the 1913/1914 season through the 1919/1920 season                                                                                                                                                                                            | 35, 41 -- 43 |
| 1920 -- 1927(?) | Philadelphia, PA                                                        | Sam performs in the Arch Street Theater, managed by {{< var mike >}}, starting in the 1920/21 season. During this time, he also performs in New York on occasion and in Atlantic City, NJ                                                                                                                             | 44           |
| 1927 -- 1928    | New York City, NY                                                       | Sam performs in the New York Public Theater, managed by {{< var schulman-full >}} and {{< var goldberg-full >}} during the 1927/1928 season.                                                                                                                                                                          | 45           |
| 1928 -- 1931    | New York City, NY                                                       | Sam performs in the Second Avenue Theater (1928/29 and 1929/30) and {{< var molly-full >}}'s Folks Theater (1930/21) with {{< var molly-full >}} and {{< var jacob-kalich >}}                                                                                                                                        | 45           |
: {.striped .hover tbl-colwidths="[10,15,55,10]"}
